### ISSUE TITLE
Required entity type in applicability (and conciseness)

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#10]
Hi,

I see that `entity` are required in the definition of applicability, while the others (classification, property and material) all have `minOccurs="0"`

https://github.com/buildingSMART/IDS/blob/2c95ab1aad74d2d4a9d01e7b54546977de2c633d/Development/Third%20production%20release/ids.xsd#L66-L68

I know of IDSs that are classification based, rather than entity based. In those scenarios the current schema would force us to repeat the classification requirement for all possible types, resulting in very large IDS files.

I would suggest that `entity` is also marked-up with `minOccurs="0"`.

Can I ask what is the benefit of forcing the declaration of entity?

**Comment by MatthiasWeise** [comment]
Additional question related to this topic: 
If I remember well entityType.name will ignore IFC inheritance, right? So, if defining a requirement for IfcBuildingElement no subtype like for instance IfcBeam will checked.

**Comment by NickNisbet** [comment]
Another reason for implementing ‘Selection’ .

Sent whilst away from my desk. 
>  
> Regards,
>  
> Nick.
>  
> Nicholas Nisbet FRSA MA(Cantab) DipArch(UNL)  
> Fellow:                              Royal Society of Arts
> Fellow:                                buildingSMART International & UKI Chapter
> Director:                            AEC3 UK Ltd
> Web:                                   http://www.aec3.com
> E-mail:                                ***@***.***
> Direct:                                +44 (0) 1494 714 933   
> Mobile:                              +44 (0) 781 616 8554              
> Skype:                                nicholasnisbet
> Registered Address:       46 St Margaret's Grove, Great Kingshill, High Wycombe, Bucks, HP15 6HP, UK
>  
> Vice-Chair:                     buildingSMART UK Chapter
> Convenor:                       buildingSMART Regulatory Room 
> 
> ********** Confidentiality Notice **********.
> This e-mail and any file(s) transmitted with it, is intended for the exclusive use by the person(s) mentioned above as recipient(s). This e-mail may contain confidential information and/or information protected by intellectual property rights or other rights. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution, copying, or action taken in relation to the contents of and attachments to this e-mail is strictly prohibited and may be unlawful. If you have received this e-mail in error, please notify the sender and delete the original and any copies of this e-mail and any printouts immediately from your system and destroy all copies of it.
>  
>

**Comment by berlotti** [comment]
@MatthiasWeise  correct

**Comment by CBenghi** [comment]
Hi @berlotti,

I'm not sure the main question has been answered,
It's not clear to me what is the benefit of forcing the declaration of entity.

Thanks,
Claudio

**Comment by berlotti** [comment]
This was changed in a later version. Hence closing this issue.
