### ISSUE TITLE
pass-globalids_are_treated_as_strings_and_not_expanded.ids

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#104]
Can anybody help me with what "expanding" means in this context?

I would think this testcase should fail, since the requested GlobalId is not equal to the one in the IFC file, but I am probably misinterpreting the intention here.

**Comment by Moult** [comment]
Fixed, the issue was with stable guid generation in the doc generator, yes the intention (as shown in the markdown, but not in the attached ifc/ids) was for the ids to be the same.

Expanding means that globalids are treated in their base64 encoded form.
