### ISSUE TITLE
Sample Data for Test Case 'Complex properties are not supported'

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#110]
The sample data (Sample IDS and Sample IFC filse) for this test case is a complex quantity instead of a complex property: 
[[FAIL] Complex properties are not supported 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#fail-complex-properties-are-not-supported-12)
dito: [[FAIL] Complex properties are not supported 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#fail-complex-properties-are-not-supported-22)

Is this intended? Sample data should be the same as in the doc?
The sample data are the sample data for the next following test case 'Complex properties are not supported' "2" - which should called 'Complex **quanities** are not supported'?

**Comment by MatthiasWeise** [comment]
I would suggest to make a note in the property facet documentation what kind of properties/quantities are in scope (all simple properties?) and what is out of scope (complex properties?).

**Comment by atomczak** [comment]
Good suggestion. Looking at the test cases, we allow simple value, bounded, list, table and enumerated properties, while don't allow complex and reference values. I added a paragraph to the property docs.
