### ISSUE TITLE
IFC-Rule for PredefinedType in partof-Test Cases

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#111]
In the IFC sample data of
- [[FAIL] A group predefined type must match exactly 2/2 - _**NB: SHOULD BE 1/2**_?](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-partof.md#fail-a-group-predefined-type-must-match-exactly-22) and [[PASS] A group predefined type must match exactly 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-partof.md#pass-a-group-predefined-type-must-match-exactly-22)
- [[FAIL] The container predefined type must match exactly 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-partof.md#fail-the-container-predefined-type-must-match-exactly-12) and [[PASS] The container predefined type must match exactly 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-partof.md#pass-the-container-predefined-type-must-match-exactly-22)
- [[FAIL] The nest predefined type must match exactly 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-partof.md#fail-the-nest-predefined-type-must-match-exactly-12) and [[PASS] The nest predefined type must match exactly 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-partof.md#pass-the-nest-predefined-type-must-match-exactly-22)

the value `'USERDEFINED'` is missing? 

E. g. `#2=IFCINVENTORY('0eA6m4fELI9QBIhP3wiLAp',$,$,$,'BUNNY',$,$,$,$,$,$);` should be `#2=IFCINVENTORY('0eA6m4fELI9QBIhP3wiLAp',$,$,$,'BUNNY','USERDEFINED',$,$,$,$,$);` ?

It's the IFC-Rule if `ObjectType`, `ElementType` or `ProcessType` has a user value `PREDEFINEDTYPE` has to be `'USERDEFINED'`?

**Comment by MatthiasWeise** [comment]
Agree to this comment. 
Thanks to @hesrah I just noted that `ObjectType` and `PredefinedType` are used interchangeable in the entity facet. However, my interpretation is also that in case of checking `ObjectType` I would expect that `PredefinedType = USERDEFINED`. 

Anyhow, I was expecting a combination of Entity and Attribut facet for user defined types (more aligned with the IFC schema), but that would not work with the partOf facet.

**Comment by lfcastel** [comment]
Is it possible this change has not been adapted in the documentation?
