### ISSUE TITLE
How to ask for specific shape representation?

### ISSUE THREAD

**Issue by Tinn-da** [buildingSMART/IDS#117]
For example, only Brep of IfcWall is needed, how to do that?

**Comment by aothms** [comment]
This is not possible in the current IDS version. It may be hard to get authoring tools to comply in every case and might contract statements from general usage or model view definitions. I'm curious to hearing more about why you want to specify this.

**Comment by Tinn-da** [comment]
Actually, I'm learning IDS and MVD these days. I was reading a master thesis in which a use case regarding geometric representation is written. The author created an MVD "only including IfcWall and a restriction to only include surface geometries" using IfcDoc. So I was wondering whether this could be achieved by IDS.
Then I looked into the repo here, the shape representation seems to be impossible currently but I was not sure, that's why I asked.

I'm not sure whether this case makes sense, if you would like to read the paper, I can send it to you.

**Comment by aothms** [comment]
I'm quite sure I've seen it thanks :) But thanks for clarifying, it is indeed a bit of an academic view on MVDs. In more recent times buildingsmart is advocating for an approach where such definitions remain compatible exchanges (e.g walls as surface geometries might hinder other use cases) and less fragmented. See here https://blog.buildingsmart.org/blog/the-curious-case-of-the-mvd Hence the current scope of IDS.

**Comment by Tinn-da** [comment]
Thanks for your hint :)
There's still so much to learn
