### ISSUE TITLE
Setting the identifier for specification as a requirement

### ISSUE THREAD

**Issue by MarcelStepien** [buildingSMART/IDS#118]
In the current version of the IDS schema, I came across the following definition:

```

<xs:complexType name="specificationType">
...
<xs:attribute name="identifier" type="xs:string">
  <xs:annotation>
    <xs:documentation>
      Author of the IDS can provide an identifier to the IDS. Beware: this cannot be enforced/assumed as (global) unique.  
    </xs:documentation>
  </xs:annotation>
</xs:attribute>

</xs:complexType>
```

As I understand it, the identifier is currently optional. However, in many cases I would like to assign and filter the validated results based on the specification. This mapping of results can and should be based on an identifier, not the name, as the name cannot be unique. 

Can someone explain to me why this identifier cannot be enforced globally? A hard definition of UUID as identifier should be able to do the trick.

**Comment by MatthiasWeise** [comment]
I would expect that name from specification is also some sort of (user-readable) identifier. If that is not unique and no identifier is available you could report about missing uniqueness of specifications.  

I wonder about the documentation: 

> Beware: this cannot be enforced/assumed as (global) unique.

Should it be unique, but we cannot specify in the IDS-XSD? 
Is not unique between different IDS files, or is may even not unique with the same IDS file? 

As summary my point of view: No need to make identifier mandatory, but some sort of documentation regarding identification suggested.

**Comment by CBenghi** [comment]
Should we improve the documentation to state that identification is the machine-readable alternative to the name?

**Comment by MarcelStepien** [comment]
I would recommend doing so. The id can be UUID based string and should be used to differentiate specifiactions. It should be required, if multiple specifications are provided. 

@CBenghi I was part of the regular meetings until the february this year. I was not aware that these meetings has been revived... Can you maybe send me another invitation?

**Comment by CBenghi** [comment]
Hi @MarcelStepien, 
we still do not have a regular schedule of meetings setup, but it should happen in the coming weeks, I'll double check that you are invited when it happens next.

**Comment by berlotti** [comment]
changed documentation to "Author of the IDS can provide an identifier to the specification. This is intended to be a machine readable identifier. Beware: because of the possibility to combine different 'requirement' elements from several ids files this cannot be enforced/assumed as (global) unique."

**Comment by atomczak** [comment]
Result: identifier stays optional because specs can be copy-pasted between IDS files.
