### ISSUE TITLE
Floating point comparisons

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#119]
Reading 

- here: https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#pass-floating-point-numbers-are-compared-with-a-1e-6-tolerance-14
- and here: #78 
- and here: #81

I wonder if it is the documentation that needs updating, or the IDS standard itself expanded as proposed in #78? Either way, something should be changed to reflect the intent and remove ambiguity.

**Comment by CBenghi** [comment]
Related to #78

**Comment by atomczak** [comment]
Resolved with #304
