### ISSUE TITLE
Structure of `info` element

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#12]
I suppose that the intended content of `info` was a sequence, instead of the stated `choice`.

https://github.com/buildingSMART/IDS/blob/2c95ab1aad74d2d4a9d01e7b54546977de2c633d/Development/Third%20production%20release/ids.xsd#L9-L19

If that's the case, I've prepared PR #9 to fix the xsd.

**Comment by CBenghi** [comment]
Furthermore having the `info` element defined with `<xs:extension>` forces it at the end of the IDS, which might not be ideal if we wanted to get the metadata of a specification without transferring/parsing the entire file, in a network environment.

If you agree I'd be happy to prepare a PR for this as well.

Thanks,
Claudio

**Comment by berlotti** [comment]
changed in latest version
