### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/IDS#123]
The [link](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/annex-b2.html) pointing to data types of IFC4x3 [property-facet](https://github.com/buildingSMART/IDS/blob/master/Documentation/property-facet.md) is wrong. The link lists things like IfcBurnerTypeEnum.

**Comment by pasi-paasiala** [comment]
Maybe the correct link is this: http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcDerivedMeasureValue.htm

**Comment by CBenghi** [comment]
@pasi-paasiala would you write a PR?

**Comment by rubendel** [comment]
This seems to have been fixed already, closing
