### ISSUE TITLE
maxOccurs should be unbounded

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/IDS#124]
In the ids [file](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/property/fail-if_multiple_properties_are_matched__all_values_must_satisfy_requirements_2_2.ids), the maxOccurs should be unbounded, since the property set contains two matching properties. So the cardinality test fails, as well as, the value test.

**Comment by CBenghi** [comment]
Closing because all test case will be evaluated by audit tool.
