### ISSUE TITLE
Links in ReadMe are incorrect

### ISSUE THREAD

**Issue by jmessner** [buildingSMART/IDS#128]
The following two links in the readme file are not correct:  
[buildingSMART IDS Template Directory](https://github.com/buildingSMART/IDS/blob/master/Documentation/todo) and more sample IFC models in the [buildingSMART IFC model directory](https://github.com/buildingSMART/IDS/blob/master/Documentation/todo).

**Comment by BigBash83** [comment]
@berlotti 
Can this be fixed? Or are the files put somewhere else. Would like to see the public template for IDS, if that is possible.

**Comment by rubendel** [comment]
This is about the following README file, I'll fix it: https://github.com/buildingSMART/IDS/blob/master/Documentation/README.md
