### ISSUE TITLE
How to specify existence check

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#13]
Looking at the recently published v0.4, I was wondering how to encode the check for the "existence of a property". That is, how to check that "FireRating"  property is specified, however, its value is not of concern?

**Comment by NickNisbet** [comment]
I would like to re-open the question of how we represent both

a.	Exceptions (“I want weight recorded on all objects except ifcOpeningElement and ifcSpace!”)  … and … 
b.	Selections (“ I want glazing-percentage recorded on all IfcDoors, IfcWindows and Grilles!”)

Adding these alongside “Requirements” and “Applicability” would complete the IDS solution and eliminate the need for ‘and’ / ‘or’ / ’not’ entities to join metrics.

 

Nick Nisbet

**Comment by pjanck** [comment]
I've opened two new issues, since the message from Nick does not really answers my question and/or contribute to its resolval.

**Comment by berlotti** [comment]
Questions from Nick answered in seperate topics.
Answer on original example requiring firerating but no specific requirements to value:

			<ids:property location="any" uri="http://identifier.buildingsmart.org/uri/dummy-example/FireRating">
				<ids:propertyset>
					<ids:simpleValue>PropertySetName</ids:simpleValue>
				</ids:propertyset>
				<ids:name>
					<ids:simpleValue>FireRating</ids:simpleValue>
				</ids:name>
				<ids:value>
					<xs:restriction>
						<xs:annotation>
						<xs:documentation>The value is not of concern</xs:documentation>
						</xs:annotation>
					</xs:restriction>
				</ids:value>
			</ids:property>



Or alternatively:  <xs:restriction><xs:pattern value="*"/></xs:restriction> if you allow any kind of value
Or alternatively:  <xs:restriction><xs:minInclusive value="0" /></xs:restriction> if you want the value to be at least 0
Or alternatively many other ways are possible with the XSD Restrictions and Facets.

**Comment by MatthiasWeise** [comment]
A technical comment: Having some value for a property is something different from having a property without a value. 
The IFC schema allows such data and in some cases it makes an important difference. However, as tools do not properly differentiate it is more an academic note than a real issue.
