### ISSUE TITLE
Type property checking

### ISSUE THREAD

**Issue by BenzclyZhang** [buildingSMART/IDS#135]
Does the property facet supports checking type property? Three different scenarios for example:
1. I want to check whether each IfcWallType has LoadBearing property
2. I want to check whether each IfcWall has LoadBearing property, either from directly associated Pset or through an IfcWallType
3. I want to check whether each IfcWall has LoadBearing property, which must be defined through an IfcWallType

**Comment by aothms** [comment]
As you can see from the test cases, IDS implementations are to follow the type object property inheritance mechanism as outlined in the IFC spec.

https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/property/pass-properties_can_be_inherited_from_the_type_1_2.ids

https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/property/pass-properties_can_be_inherited_from_the_type_1_2.ifc

So

1. possible, applicability IfcWallType, requirement property
2. possible, applicability IfcWall, requirement property
3. not possible

There used to be something like a location=occurence|type on the property facet to allow for 3, but the argument against it was that it could contradict the ifc spec (we have occurencedriven and all in the spec) and that it would make sth explicit that normal users don't care about or maybe cannot influence in their tools.

**Comment by CBenghi** [comment]
Closing after long inactivity.
