### ISSUE TITLE
Agree how to deal with standard cases

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/IDS#146]
The current version of IDS does not consider inheritance in the IFC schema. That is fine. However, I don't see a point in differentiating between IFCWALL and IFCWALLSTANDARDCASE, since the users typically don't make a difference between these.

I see two solutions:
1. Always when a tool that is exporting IDS sets the entity type to IFCWALL, the resulting IDS will contain an enumeration with IFCWALL and IFCWALLSTANDARDCASE
2. The software that check the IDS specification treat IFCWALL and IFCWALLSTANDARDCASE equal

I'd go with the second option, since it is likely that there will be IDS files where the enumeration is missing and there's unnecessary discussion with the end users why this is the case. To save this effort, the checking software may end up implementing this anyway.

**Comment by Moult** [comment]
It seems yet again that the decision should be made to support inheritance: https://github.com/buildingSMART/IDS/issues/86

Handling these little edge cases are pretty frustrating. Both options are little "gotchas" for implementers.

**Comment by aothms** [comment]
Well, as discussed, enabling inheritance in evaluation will also result in unexpected (or undesirable) features. Such as the IFC4.3.IfcBuiltElement which has two "functions" (a) the supertype of build(ing) elements (b) the designated entity for use when no applicable element is found (the old proxy elem basically). Without inheritance both of these cases are nice and separated. In my view it's simply a matter of fact that the IFC schemas has too many quirks to expect end-users to make sense/use of inheritance.

Also, with the standard cases being deprecated/partly removed, it warrants some special casing.

These kind of (evaluation-time) expansion rules were also discussed here for type objects without a missing occurence. https://github.com/buildingSMART/IDS/issues/116#issuecomment-1313439557 I would also here go with option 2.

**Comment by pasi-paasiala** [comment]
@Moult I'm pretty optimistic that this is the only thing related to inheritance we'd need to implement. Also, if we'd add support for generic inheritance, that might limit the people willing to implement IDS, for example, inside of a CAD tool since they should be aware of the IFC inheritance there and even which schema they should consider even before they've exported their model to any IFC.

**Comment by CBenghi** [comment]
> (a) the supertype of build(ing) elements (b) the designated entity for use when no applicable element is found (the old proxy elem basically). Without inheritance both of these cases are nice and separated

@aothms, would a flag to include/exclude inheritance solve your objection?

**Comment by berlotti** [comment]
Inheritance is an ongoing/returning debate.
It can be argued both ways.

The use-cases that require this are minimal, while the risk of invalid behaviour in implementations grows exponentially.
The project made the decision in the beginning to not support it and that still seems the correct decision.

We can always reevaluate after 1.0
