### ISSUE TITLE
Possible problem in the schema?

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#15]
https://github.com/buildingSMART/IDS/blob/4657203905e1c5fbd0512e505bd8c5776a863fc8/Development/0.4/ids_04.xsd#L55

The XSD converter from Microsoft complains that `ref="xs:restriction"` is not defined.

I tried correcting to `type="xs:restriction"` (guessing here that this was what was meant), the attribute still needs a name. What would that be?

**Comment by berlotti** [comment]
xs namespace is is defined in the header of the XSD.
XML Spy, Notepad++ and Eclipse have no issues.

**Comment by pjanck** [comment]
> xs namespace is is defined in the header of the XSD

That wasn't the question. My concern is about the `ref` attribute of the `xs:element`. 

> XML Spy, Notepad++ and Eclipse have no issues.

Neither has Sublime Text. However, I am uncertain that any of these tools also check that the *content* of the schema (not its syntax) is correct.

I did some additional digging [here](https://www.w3schools.com/xml/el_element.asp):

![grafik](https://user-images.githubusercontent.com/59165496/134650721-7f6ee415-a5ac-4b39-af1c-5096d8acce9e.png)

`xs:restriction` is a *built-in data type* of the namespace `xs`, right? Therefore it should be `type` and not `ref` in my opinion.

I request to reopen the issue.
