### ISSUE TITLE
Example on double negative

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#150]
Reading here: https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-ids.md#pass-a-prohibited-specification-and-a-prohibited-facet-results-in-a-double-negative

I wonder if the green ticks are correct in the evaluation:

![grafik](https://user-images.githubusercontent.com/59165496/230008595-36c75347-31a2-43c6-bf0f-ff75f2259e0b.png)

I think that the bottom two should be red crosses, since they are prohibited.

**Comment by CBenghi** [comment]
I also doubt that the double negative is what we intended when we discussed the schema.

The intent was to prohibit the existence of some entities, not negate their traits.

I think that a prohibited specification should have no requirements.

**Comment by aothms** [comment]
I think this was something we discussed extensively on slack, but we can't view it anymore due to the 90d message history limit 😡 

I think the discussion was something like: " not exists( appl -> requirement ) " is indeed potentially problematic. Especially with negations involved and not having a formal underpinning of our schema.

> I think that a prohibited specification should have no requirements.

That was one of the solutions discussed and I think the best one.

**Comment by Moult** [comment]
The green ticks make sense to me. The spec passes.

A double negative makes a positive.

 1. Facet "The name is Waldo": True.
 2. Prohibited Facet: False.
 3. Prohibited Spec: True.

**Comment by arishinsemen** [comment]
Please comment each point below. How i understand this test case

1. "Prohibited" specification tag does not affect to applicability (Can't formulate applicability "not IFCWALLL")
2. "Prohibited" specification tag is the same to I add "Prohibited" tag to all requirement. Logic rule NOT (A AND B) = (NOT A) OR (NOT B) does not work.
3. Double "Prohibited" (specification and requirement tag) "destroy" both

**Comment by CBenghi** [comment]
Closed with consensus of the call since the case does not apply to the implementation agreements of the latest schema.
