### ISSUE TITLE
How to represent exceptions

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#16]
I would like to re-open the question of how we represent

a.	Exceptions (“I want weight recorded on all objects except ifcOpeningElement and ifcSpace!”)

_Originally posted by @NickNisbet in https://github.com/buildingSMART/IDS/issues/13#issuecomment-885714038_

**Comment by NickNisbet** [comment]
The solution is (would be) to duplicate the "Applicability" entity as an "Exception"  and as a "Selection" entity. 
The semantics of  the existing "Requirement" is that each entry is joined by an implied "and"
The semantics of the existing "Applicability" is that each entry is joined by an implied "notand"
The semantics of "Exception" is that each entry is joined by an implied "or"
(The semantics of "Selection" is that each entry is joined by an implied "notor".)
The four structures together can express most needs. The Specification is met if one or more the four entities evaluate to true (another implicit 'or').
However recursioncould be needed to express **any** highly qualified expectations,. This can be supported by allowing a Specification  as a metric, just like the type, classification or property tests etc.

**Comment by berlotti** [comment]
Exceptions have been declared out of scope for the first version. It is on the roadmap for future versions.

However.... in the current version, you could use this XSD Pattern in the applicability section for your specific example:
^(?!IfcOpeningElement$|IfcSpace$).*

**Comment by aothms** [comment]
Since currently inheritance is out of scope, it isn't possible anyway to make very general statements (for better or worse) and exceptions in the sense as defined above on entity types have less utility.
