### ISSUE TITLE
IFCVersion attribute

### ISSUE THREAD

**Issue by cicciopage** [buildingSMART/IDS#160]
Hi to all, 
according to XSD, the "ifcVersion" attribute in the Specification node must be present but it could be empty. Why is this necessary?
Maybe, if the attribute is required, at least one value must be present.

**Comment by berlotti** [comment]
Nice catch! 
Should probably be at least a value indeed.

**Comment by CBenghi** [comment]
Empty schema is caught by the Audit tool as an error.
I'm not sure if this can be specified in the xsd too.

**Comment by berlotti** [comment]
added <xs:minLength value="1"/> restriction  to ifcVersion list

**Comment by cicciopage** [comment]
is this issue still opened? I checked that minLength restriction was added to the last xsd version

**Comment by berlotti** [comment]
correct; will close
