### ISSUE TITLE
Use of xs:extensions in the schema

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#162]
This is a just matter of tidiness of the schema file, no substance would be changed.

In a few locations of the schema, `xs:extensions` use seems redundant because they do not add any data.

https://github.com/buildingSMART/IDS/blob/24d01a14b075f31ee1172f373720512fdbc3c105/Development/ids.xsd#L30-L36
https://github.com/buildingSMART/IDS/blob/24d01a14b075f31ee1172f373720512fdbc3c105/Development/ids.xsd#L71-L77
https://github.com/buildingSMART/IDS/blob/24d01a14b075f31ee1172f373720512fdbc3c105/Development/ids.xsd#L113-L121

Also for requirements,

https://github.com/buildingSMART/IDS/blob/24d01a14b075f31ee1172f373720512fdbc3c105/Development/ids.xsd#L200-L208

The type is only used here, so no need to use extension, we can just add  `description` to `requirementsType`.

**Comment by berlotti** [comment]
I think it needs to be like this to be valid XSD.
What would be the alternative? Do you have an example?

**Comment by berlotti** [comment]
merged with [4149538](https://github.com/buildingSMART/IDS/commit/4149538733196f7365c3709b63ceab4b4dcc0069)
