### ISSUE TITLE
How to represent Selections

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#17]
I would like to re-open the question of how we represent

b.	Selections (“ I want glazing-percentage recorded on all IfcDoors, IfcWindows and Grilles!”)
 
_Originally posted by @NickNisbet in https://github.com/buildingSMART/IDS/issues/13#issuecomment-885714038_

**Comment by berlotti** [comment]
The answer was use of XSD Patterns or Facets.
For example something like this:


<ids:specification name="Human readable name for the objects; for example Grilles" necessity="required">								
		<ids:applicability>
			<ids:entity>
				<ids:name>
					<xs:restriction>
							<xs:pattern value="(IfcWindows|IfcDoors).*" />
					</xs:restriction>
				</ids:name>
			</ids:entity>
		</ids:applicability>
		<ids:requirements>
		<ids:property location="any">
				<ids:propertyset><ids:simpleValue>Example for Stefan</ids:simpleValue></ids:propertyset> 
				<ids:name>
					<ids:simpleValue>glazing-percentage</ids:simpleValue>	
				</ids:name>
				<ids:value>
					<xs:restriction>
						  <xs:pattern value="[0-9][0-9]" />
					</xs:restriction>
				</ids:value>
		</ids:property>
             </ids:requirements>
</specification>

Also added the pattern that the value of the glazing-percentage needs to be 2 numbers.
