### ISSUE TITLE
Question about TypeEnums

### ISSUE THREAD

**Issue by giuseppeverduciALMA** [buildingSMART/IDS#174]
I would like to ask a question about TypeEnums.

For example, I have the following ifc file:

~~~lua
#1=IFCWALL('1hqIFTRjfV6AWq_bMtnZwI',$,$,$,$,$,$,.SOLIDWALL.);
~~~

Is it correct that this requirement fails?
~~~xml
<attribute>
  <name>
    <simpleValue>PredefinedType</simpleValue>
  </name>
  <value>
    <simpleValue>.SOLIDWALL.</simpleValue>
  </value>
</attribute>
~~~

and the following requirement passes?

~~~xml
<attribute>
  <name>
    <simpleValue>PredefinedType</simpleValue>
  </name>
  <value>
    <simpleValue>SOLIDWALL</simpleValue>
  </value>
</attribute>
~~~

so, the correct value is without dots as the ifc documentation (https://standards.buildingsmart.org/MVD/RELEASE/IFC4/ADD2_TC1/RV1_2/HTML/schema/ifcsharedbldgelements/lexical/ifcwalltypeenum.htm)?

Thanks

**Comment by Moult** [comment]
Yes. The dots are merely the way IFC-SPF (.ifc file) handles enums but have no significance on the data.
