### ISSUE TITLE
Is xs:sequence intended?

### ISSUE THREAD

**Issue by Moult** [buildingSMART/IDS#175]
Because xs:sequence is used, that means that the description element must be exactly in that position and in no other. Is this intentional? Sounds like it's just a pain with no real meaning.

I've noticed others and most recently https://github.com/IfcOpenShell/IfcOpenShell/issues/3476 who seem to write IDSes by hand run into this problem.

**Comment by berlotti** [comment]
According to my XMLSpy validation this is the only valid way to construct the XSD. I think it has to do with the reuse of parts of the schema. 
If we can get it in random order but still have valid XSD I'm happy to change it.

**Comment by andyward** [comment]
Sounds like it should be `xs:all` with the appropriate min/maxOccurs?

> all: The elements can occur in any order.  https://www.w3.org/TR/xmlschema11-1/#element-all

**Comment by NiklasPor** [comment]
I can only second @andyward. I was very confused when I came across this while giving a TS implementation a try. If the order isn't adding any value please us `xs:all`, otherwise it'll take extra effort in all implementations to keep the xml tags in the right order 👍

**Comment by berlotti** [comment]
ok; looking for feedback from others as well

**Comment by CBenghi** [comment]
There's no semantic need for constraining the order.

I second the schema change that Andy suggests. It is more tolerant, but
retains backwards compatibility.

**Comment by NiklasPor** [comment]
@SergejMuhic FYI querying by index might be dangerous, as a lot of the items in the sequences are optional (marked with `minOccurs=0`).

**Comment by SergejMuhic** [comment]
> @SergejMuhic FYI querying by index might be dangerous, as a lot of the items in the sequences are optional (marked with `minOccurs=0`).

Missed that. I will not query by index! 😄

**Comment by CBenghi** [comment]
`xs:sequence` is used in many places across the schema. Are we intending to replace it everywhere with `xs:all`?

**Comment by CBenghi** [comment]
In the call we have identified some value of keeping sequences in order:

- Comparing two versions of the file
- Producing text version of the content in a reliable and consistent way

So the decision is to keep the sequence elements.
