### ISSUE TITLE
Testcase is wrong?

### ISSUE THREAD

**Issue by mysterieux30** [buildingSMART/IDS#187]
I think something is wrong with this testcase unless there is a missunderstood from my side.

Link:
https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-ids.md#pass-multiple-specifications-are-independent-of-one-another

Why does the line `#2=IFCWALL('0eA6m4fELI9QBIhP3wiLAp',$,'Waldo',$,$,$,$,$,$);` pass both tests, it should not pass the test of the first specification where it is mentionned that every IFCWALL must have a Description with "Foobar" as value (double negative).

**Comment by Moult** [comment]
Yeah it looks suspicious, probably some really mind-bending double negative voodoo going on here. I'd love to test it in detail but unfortunately prohibited attributes have now been removed due to #144.

**Comment by CBenghi** [comment]
Closed because the test case has been removed.
