### ISSUE TITLE
Correct cardinality for restriction

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#204]
Hello,

I think there is a problem in the schema with the cardinality definition of restrictions. 

https://github.com/buildingSMART/IDS/blob/10b5edfa2614684cf014a9909e5b20e76574c12d/Development/ids.xsd#L39-L44

Should not the value for `maxOccurs` on `xs:restriction` be `1`, instead of `unbounded`?

**Comment by aothms** [comment]
Don't we need multiple for combining min+maxInclusive? (Although I agree, in an ideal world that would have been one dedicated value range restriction - as other combinations of restrictions don't make a lot of sense in the case of IDS).

**Comment by CBenghi** [comment]
I'm not sure what you mean there, restriction is an xml element alternative to `simpleValue`

For allowing multiple possible values, options can be multiplied inside the single restriction element, such as:

```xml
<xs:restriction base="xs:string">
	<xs:enumeration value="SomeValue" />
	<xs:enumeration value="SomeOtherValue" />
</xs:restriction>
```

In my view the schema should change to:

```xml
<xs:complexType name="idsValue"> 
 	<xs:choice minOccurs="1"> 
 		<!-- place for potential additional rules for idsValue --> 
 		<xs:element name="simpleValue" type="xs:string" minOccurs="1" maxOccurs="1"/> 
 		<xs:element ref="xs:restriction" minOccurs="1" maxOccurs="1"/> 
 	</xs:choice> 
```

**Comment by aothms** [comment]
> I'm not sure what you mean there, restriction is an xml element alternative to simpleValue

Ok thanks, then disregard my comment, confusion on my side, too far out of the loop I guess.
