### ISSUE TITLE
Interpretation of material requirements

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/IDS#21]
There are [different kinds of material definitions in IFC (single material, material layers, material constituent, material profile)](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcmaterialresource/lexical/ifcmaterialselect.htm). Material requirements in IDS define a single value only. 

How to implement checking of material requirements? 
Is it focused on [single material](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/templates/material-single.htm) only, and checking of the IfcMaterial.Name attribute?

**Comment by berlotti** [comment]
This is identified as something to be decided together with the vendors in phase 2 of the project.

**Comment by Moult** [comment]
This has been documented and included in test cases, so closing.
