### ISSUE TITLE
IDS roadmap - scope of IDS 1.1, 2.0, 2.1 and 3.0 as announced in the strategic roadmap?

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/IDS#210]
BSI's [strategic roadmap](https://www.buildingsmart.org/about/strategic-roadmap/) announces a new IDS version every year from now on. 
What is the expected scope of these versions? @berlotti Can you please update the [IDS roadmap](https://github.com/buildingSMART/IDS/blob/master/Development/Roadmap.md)?

**Comment by berlotti** [comment]
Scope will be determined by use-cases and input from vendors.
Implementer Forum and Implementer Assembly will provide input. SCTE will define scope based on input.

**Comment by MatthiasWeise** [comment]
Certainly not all details are settled down yet, but I was expecting some kind of high-level scope definition behind this diagram, in particular as it shows dependencies to bSDD and other specifications.

**Comment by atomczak** [comment]
1.1 will contain minor updates to 1.0 that will allow IDS certification and is planned for 2024Q4/2025Q1. 

2.0 is planned to be developed together with the next version of IFC (as show on the roadmap). The milestones here on github give a good indication of the aspects to be included.
