### ISSUE TITLE
Repeatability of material facet

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#211]
The material facet is not repeatable in the collections, but it's not clear why.
The documentation does not mention it.

I would argue that it should be repeatable both in applicability and in requirements.

**Comment by MatthiasWeise** [comment]
Would it makes sense to ask several times for existence of material?
If you provide options for material names, you should be able add enumerations or define a pattern.

**Comment by NickNisbet** [comment]
This would be Selections by the back-door.
Which would be Weird when other repeated facets mean cumulative Applicability or cumulative Requirements.

Regards,

Nick.

Nicholas Nisbet FRSA MA(Cantab) DipArch(UNL)
Director:                            AEC3 UK Ltd
Direct:                                +44 (0) 1494 714 933
Mobile:                              +44 (0) 781 616 8554
 ***@***.***

Fellow                      Royal Society of Arts
Fellow                      buildingSMART International and buildingSMART UKI
Leader:                     buildingSMART International Regulatory Room
Vice-Chair:               buildingSMART UKI Chapter

Member: UK BSI CB/5  Digitalization of the built environment and B555 Construction Information
Development of ISO 12006-2 on Classification structures and Breakdown structures
Development of ISO 19650-6 on Collaborative BIM for Health and Safety
Development of ISO 22014 on BIM library objects
Development of ISO 15686-3 Buildings and constructed assets - Service life planning: Part 3, Information and Calculations


********** Confidentiality Notice **********.
This e-mail and any file(s) transmitted with it, is intended for the exclusive use by the person(s) mentioned above as recipient(s). This e-mail may contain confidential information and/or information protected by intellectual property rights or other rights. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution, copying, or action taken in relation to the contents of and attachments to this e-mail is strictly prohibited and may be unlawful. If you have received this e-mail in error, please notify the sender and delete the original and any copies of this e-mail and any printouts immediately from your system and destroy all copies of it.




From: Claudio Benghi ***@***.***>
Sent: 24 October 2023 09:51
To: buildingSMART/IDS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [buildingSMART/IDS] Repeatability of material facet (Issue #211)


EXTERNE-EMAIL Bitte klicken Sie nicht auf Links oder öffnen Sie keine Anhänge! Es sei denn, Sie kennen den Absender und wissen, dass der Inhalt sicher ist.

The material facet is not repeatable in the collections, but it's not clear why.
The documentation does not mention it.

I would argue that it should be repeatable both in applicability and in requirements.

**Comment by andyward** [comment]
> If you provide options for material names, you should be able add enumerations or define a pattern.

Enums / patterns would be a logical OR wouldn't they?

How would we express the following specification without multiple materials facets on Applicability?

> All IfcBeams constructed of both Material 'Aerated Concrete' **and** Material 'Steel' must provide a Property 'Pset_ConcreteElementGeneral.ExposureClass'

Looks to me like the only facet that is genuinely 0:1 is Entity - all the others should be 0:* if we're being consistent

**Comment by MatthiasWeise** [comment]
Good example for the need of AND with material applicability! 
0:* makes sense then.
