### ISSUE TITLE
Prohibited specification with an optional requirement

### ISSUE THREAD

**Issue by mysterieux30** [buildingSMART/IDS#219]
Hi, I wanted to ask if it is allowed to create a prohibited specification containing an optional requirement. In this case how should i interpret it ?

**Comment by CBenghi** [comment]
You could not.
A prohibited specification can contain no requirements. Only the applicability will be filled in.
Facets in the applicability have no cardinality.

**Comment by CBenghi** [comment]
@mysterieux30 please reopen if you have further questions.
