### ISSUE TITLE
Inaccurate using of word "entity".

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/IDS#220]
I think it is incorrect using of word "entity" in https://github.com/buildingSMART/IDS/blob/master/Documentation/entity-facet.md

>>> "Every entity in an IFC model has an "IFC Class" Name. For example, wall entities will have an IFC class of IfcWall"

In my mind "instance" should be used instead of "entity", while "entity" is a synonym of "IFC class".

Compare EXPRESS "ENTITY IfcWall..." with C++ "class IfcWall" and with EXPESS using of TYPE,
Also refer to sdaiGetEntity and sdaiGetInstance

**Comment by aothms** [comment]
I agree! Either "entity instance" or just "instance'. A Pull Request would be great :)

**Comment by I-Sokolov** [comment]
Made PR https://github.com/buildingSMART/IDS/pull/230

**Comment by CBenghi** [comment]
Thanks @I-Sokolov, I'll close this and merge the PR before 1.0.
