### ISSUE TITLE
IDS Rule - Floating point numbers are compared with a 1e-6 tolerance 1/4

### ISSUE THREAD

**Issue by Minna26** [buildingSMART/IDS#221]
Hi,

Can you please guys check this IDS Rule: [Floating point numbers are compared with a 1e-6 tolerance 1/4](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#pass-floating-point-numbers-are-compared-with-a-1e-6-tolerance-14)

To me, it seems like the comparison is with 1e-4. It seems that the number is rounded to four decimals and then compared.
Can you clarify for me how this is compared?
Thank you.

**Comment by mysterieux30** [comment]
Same question, i think you are right Minna26

**Comment by atomczak** [comment]
The group has reached a conclusion, and @giuseppeverduciALMA summarised it in #294. Closing this issue. If needed, please continue in #78.
