### ISSUE TITLE
Some issues in test-cases

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/IDS#224]
Generally speaking, I'm impressed the documentation is short, full and easy to follow.
Of course, always there is a space for minor issues:)

Many examples use like this:                 attribute minOccurs="1" maxOccurs="1"

It violates:
![image](https://github.com/buildingSMART/IDS/assets/6941925/93fc3fbe-94e7-4b91-899d-f3906887aa42)

Maybe it is better to update doc rather than test-cases?

**Comment by andyward** [comment]
Fixed by #240 I believe, when introducing _cardinality_ attribute on Requirement facets
