### ISSUE TITLE
test-case error? pass-occurrences_override_the_type_classification_per_system_1_3

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/IDS#225]
[IDS](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/classification/pass-occurrences_override_the_type_classification_per_system_1_3.ids) requires any IfcWall must have classification ref "11".  
[IfcWall #4](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/classification/pass-occurrences_override_the_type_classification_per_system_1_3.ifc) has no classification reference itself nor by type.  
Should not test-case fail?

**Comment by I-Sokolov** [comment]
@pasi-paasiala wrote he fixed it but I'm still observing.
Made PR

**Comment by andyward** [comment]
Yes, but I think Pasi suggested it be fixed for 1.0 - I think there's a PR to regen the test cases and hope it can be picked up with that: #192. Have added some notes to that PR linking yours in.

**Comment by CBenghi** [comment]
I think this one has been fixed in #240 which we hope to merge soon. Closing this as duplicate, anyway.
