### ISSUE TITLE
pass-the_container_may_be_indirect, should it really pass?

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/IDS#227]
The IDS requires partOf with relation="IfcRelContainedInSpatialStructure".

In the IFC mode the beam is aggregated into slab and slab is contained in space.

As documentation says, "only the specified relation type should be considered (also recursively)" - the beam does not fit to this requirement.

Semantically it should, so I assume documentation needs special case and clarification for spatial containment.

**Comment by CBenghi** [comment]
@atomczak,
you are also right we that we need to add another test case for multiple relations of the same type.
