### ISSUE TITLE
`type` instead of `ref`?

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/IDS#23]
Since #15 was prematurely closed, I'm opening a new issue to raise my concerns:

https://github.com/buildingSMART/IDS/blob/4657203905e1c5fbd0512e505bd8c5776a863fc8/Development/0.4/ids_04.xsd#L55

I did some digging [here](https://www.w3schools.com/xml/el_element.asp):

![grafik](https://user-images.githubusercontent.com/59165496/134650721-7f6ee415-a5ac-4b39-af1c-5096d8acce9e.png)

`xs:restriction` is a *built-in data type* of the namespace `xs` not an element, right? Therefore it should be `type` and not `ref` in my opinion.

**Comment by aothms** [comment]
`xs:restriction` is not a built-in data type. Those are listed here in the spec https://www.w3.org/TR/xmlschema-2/#built-in-datatypes

I also want to stress the obligatory https://www.quora.com/Is-W3Schools-a-reliable-source here I don't think we should base our decisions on that source.

Also there are apparently other issues with xsd.exe handling ref incorrectly (although not very similar to this case) https://stackoverflow.com/questions/44028046/how-to-use-xsd-exe-with-attributegroup-ref I personally have mixed experience with automated codegen from XSD.

In my understanding, but I'm not an XML/XSD expert, and I know @berlotti has consulted people infinitely more knowledgeable than me on this regard, it's as you hinted on in the other issue, in this case mostly a matter of taste. When you use `type`, you declare something of that type but still need to give it a name local to your schema [in XML files that adhere to the schema you see the local name]. When you use ref you basically nest that thing verbatim in your schema [in XML files that adhere to the schema you see xs:restriction].

Another difference, but not relevant, but what's described in your table, is that `type` can only be used for, well, types. And ref is much more general, can be used for identifiable elements, including types.

**Comment by berlotti** [comment]
It is an explicit choice to use the xs:restriction as is. We don't want to create an IDS restriction of the same type as an xs:restriction, but use the actual xs:restriction. This brings a lot of added value with the ability to use multiple toolkits for xs:restriction saving implementation time and adding consistency.

Combining two namespaces was a deliberate choice.  The use of two namespaces in the XSD is not common, but valid.

Closing this issue.
