### ISSUE TITLE
Construction phase/LOI related IDS Check

### ISSUE THREAD

**Issue by masterblogger** [buildingSMART/IDS#232]
A question about the attribute check of the IDS with reference to phases. As far as I can see the examples and documentation
Nowhere has a phase been defined from which an attribute / an attribute value is defined
must be present. All requirements of the IDS are therefore always compared with the IFC without the phase in which they are
IFC is located would be taken into account.

From the perspective of an ongoing project, the IDS makes sense because it contains all the attributes to be delivered
contains, but these are always checked as a whole. Due to the fact that certain attributes / attribute values
will only be present in the model in later phases - such as product attributes such as manufacturer
or serial number - comparing an IFC with the IDS results in unnecessary not being relevant
Missing attributions can be found because they cannot yet be provided.

An selection of attributes an the phase on which those needed to be check:
![image](https://github.com/buildingSMART/IDS/assets/20327806/222c3331-4996-492f-b074-24b006d5c1ff)

In particular, it should be possible to attribute according to a phase such as the planning phase or construction phase
or a LOIN. However, it currently looks like the IDS only
as a tool for testing as-built models - if all information is available.

The main question is therefore whether it is planned for the IDS to be able to check attributions for each phase?

Furthermore, the question arises as to whether a period of time can be specified within which attributions must be made.
so that, for example, the attribute BSMART_Variant can only be used in the planning phase but not in later phases.

**Comment by andyward** [comment]
Every IDS file has a **Milestone** property in the [metadata](https://github.com/buildingSMART/IDS/blob/master/Documentation/ids-metadata.md). So Milestone should contain your Phase name. This means you'd have multiple IDS files split by phase (& potentially **Purpose**).

**Comment by atomczak** [comment]
Resolution: the IDS Purpose and Milestone now closely align with Purpose and Milestone description from the LOIN standard (EN17412). A user can use that IDS metadata to reference/implement their LOINs. The current limitation is that one IDS file (containing many specifications) can only refer to one pair of purpose and milestone. In the future version of IDS, it should be considered if it should be possible to address many LOINs in one IDS file. Moving to milestone 2.0.
