### ISSUE TITLE
IDS XSD Specification / Versions

### ISSUE THREAD

**Issue by quasarchimaere** [buildingSMART/IDS#235]
So i have somewhat of an Issue, i am able to get the Dev/Draft of the IDS Specification in a Version that is unknown to me. However i know that there are Files of already published versions out there (specifically 0.9.3 and 0.9.6) and i can't seem to find any of them anywhere.

Is there a specific URL or Repo where i can get the published (immutable) xsd files for the specific IDS Versions?

I would need them/it to be able to generate version dependent Java-Classes

**Comment by MarcelStepien** [comment]
The current version is listed as **ids.xsd** in the following path:

https://github.com/buildingSMART/IDS/tree/master/Development

**Comment by quasarchimaere** [comment]
> The current version is listed as **ids.xsd** in the following path:
> 
> https://github.com/buildingSMART/IDS/tree/master/Development

as seen in my first sentence this is exactly what i was refering to, i know that there is a dev/draft of the ids.xsd (thank you for the link anyway) but there are no "fixed" versions of previous iterations found on the web, which makes it hard for anybody (including me) to properly support exports of ids files using an older schema (like where is the spec for 0.9.3 for example)

**Comment by berlotti** [comment]
Releases are https://github.com/buildingSMART/IDS/releases 
(or in the history of https://github.com/buildingSMART/IDS/commits/master/Development/ids.xsd)
