### ISSUE TITLE
Very bad documentation for XSD validation

### ISSUE THREAD

**Issue by LukasKStavario** [buildingSMART/IDS#236]
Hi I have decided to develop and support XSD import and export from our IFC validation tool. 
If I download any of your examples and validate it by your provided XSD in online tools, every tool shows much errors. You have provided bad schemas and your schema does not exist (in time maybe).

**Comment by berlotti** [comment]
The XSD of IDS combines two namespaces; the one from IDS and the xsd restrictions.
The combination of namespaces is advanced use, but valid XSD. Not all tools support it.
There has been quite some discussion about it already. Sure you can find it when searching the repo.

Please be aware that this repo also falls under the buildingSMART behaviour guidelines and policies. Your comment is not complying with the way of communicating that we are used to.

**Comment by LukasKStavario** [comment]
Your example (or official ids.xsd) has corrupted default xml namespaces and has links to not existing files on w3. Is it possible to develop and validate ids now or is it only prealpha?

sure I have seen two namespaces but there is no problem with that. I will edit my previous comment in the name of censure.

**Comment by berlotti** [comment]
The XSD validators that I use all return that this XSD is valid.
Are we talking about the official ids.xsd here https://github.com/buildingSMART/IDS/blob/master/Development/ids.xsd ?
What examples are you talking about?
Please be more specific.

**Comment by LukasKStavario** [comment]
I am sorry, I have finally reach the function validation in C#. I was very confused of this 3 schemes - that 2 points to same schemeLocation.
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:import namespace="http://www.w3.org/2001/XMLSchema" schemaLocation="http://www.w3.org/2001/XMLSchema.xsd"/>
	<xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.w3.org/2001/XMLSchema-instance"/>
Closing and sorry!

But if you want points to better documentation I can prepare some example.
