### ISSUE TITLE
XSD is invalid for data classes tools

### ISSUE THREAD

**Issue by AndreeHub** [buildingSMART/IDS#239]
So the current .xsd file cannot be used to generate data classes automatically using Microsoft xsd.exe tool.
Is there some other tool that works?
Are there some already existing data classes that we can use?

**Comment by CBenghi** [comment]
Hello @AndreeHub,

there is a target command in the repository that will create the classes in c# for you.

use `build CleanSchemaProject` from command line or `./build CleanSchemaProject` from powershell to get the classes created.

Note, you might want to wait a couple of days until we merge 0.9.7 in main. Please close the issue if resolved.

**Comment by AndreeHub** [comment]
Thank you for the reply . Can you give me a bit more info?  Do you mean this repo or the Audit tool ? I cant find this command even on search.  Is there a guide how to use it somewhere?

**Comment by CBenghi** [comment]
The command is found in the `build/Build.cs` file, but the correct version is not yet merged in master.
You can see it at this link:

https://github.com/CBenghi/IDS/blob/0f2a33268f9b41e5095fb0d9dd06af9a791c832f/build/Build.cs#L31

The project in the `SchemaProject` has some other classes that you can use to import/export the entire schema.

If you checkout `https://github.com/CBenghi/IDS/tree/facetsReview` then issue the command `build CleanSchemaProject` from the root git folder it will create the csharp class for you (you need the dotnet runtime 6.0 installed).

**Comment by CBenghi** [comment]
@AndreeHub, just to let you know that the PS has been merged, so you can work on the master branch, to look into this.

**Comment by CBenghi** [comment]
Hello @AndreeHub, 
I'm closing the issue, considering it resolved.
Re-open it if you are still having problems.
