### ISSUE TITLE
0.4.3 XSD

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#24]
When trying to generate Java classes from the XSD, I had to remove line 7 from the XSD. I don't think it is required.

Anyone with more experience in XSD/XML known why it is there?

```xml
<xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.w3.org/2001/XMLSchema-instance"/>
```

**Comment by MarcelStepien** [comment]
I encountered the same issue using the JAXB library. The main problem, is that the link in schemaLocation is not pointing to a XSD schema. You can just remove the schemaLocation and it works fine. Typing the link into the Browser also reveals the information:

"This schema should never be used as such"

For schemaLocation the link to the "XMLSchema-instance.xsd" needs to be provided to resolve the issue, or simply remove the entry if it is not needed.
