### ISSUE TITLE
Expected datatype for EnumeratedProperties?

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/IDS#245]
I am using http://www.xbim.it/ids to check our IDS files and it reports the following error for Pset_BeamCommon.Status.

> Error Error 103: 
> Invalid datatype `IFCLABEL` (no valid values exist) in the context of Ifc4x3 on 'property' element at line 97, position 10.

```
        <ids:property instructions="Status" datatype="IFCLABEL" minOccurs="1" maxOccurs="unbounded">
          <ids:propertySet>
            <ids:simpleValue>Pset_BeamCommon</ids:simpleValue>
          </ids:propertySet>
          <ids:name>
            <ids:simpleValue>Status</ids:simpleValue>
          </ids:name>
        </ids:property>
```

IFCLABEL seems to be wrong here. @CBenghi What is the correct/expected datatype?

I wonder, because existing IFC files seems to use IFCLABEL as underlying datatype, e.g. 

`#1401625=IFCPROPERTYENUMERATEDVALUE('Status',$,(IFCLABEL('EXISTING')),#1076681);`

**Comment by CBenghi** [comment]
Hi @MatthiasWeise,
can you give this another try? 
I've updated the code, and it should be ok now (provided that you update to the latest schema with `baseName`).
