### ISSUE TITLE
Documentation of uri on facet

### ISSUE THREAD

**Issue by NickNisbet** [buildingSMART/IDS#249]

**Comment by CBenghi** [comment]
Hi Nick, are you suggesting to add documentation inside the XSD or in the markdown documents?

**Comment by NickNisbet** [comment]
‘Implementers agreements’ should be documented in the xsd. They are restrictions not encoded in xsd structures. They are not supporting documentation (ideas, examples etc) which can stay in the md files .

Sent whilst away from my desk.

Regards,

Nick.

Nicholas Nisbet FRSA MA(Cantab) DipArch(UNL)
Fellow:                              Royal Society of Arts
Fellow:                                buildingSMART International & UKI Chapter
Director:                            AEC3 UK Ltd
Web:                                   http://www.aec3.com<http://www.aec3.com/>
E-mail:                                ***@***.******@***.***>
Direct:                                +44 (0) 1494 714 933
Mobile:                              +44 (0) 781 616 8554
Registered Address:       46 St Margaret's Grove, Great Kingshill, High Wycombe, Bucks, HP15 6HP, UK

Vice-Chair:                     buildingSMART UK Chapter
Convenor:                       buildingSMART Regulatory Room

********** Confidentiality Notice **********.
This e-mail and any file(s) transmitted with it, is intended for the exclusive use by the person(s) mentioned above as recipient(s). This e-mail may contain confidential information and/or information protected by intellectual property rights or other rights. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution, copying, or action taken in relation to the contents of and attachments to this e-mail is strictly prohibited and may be unlawful. If you have received this e-mail in error, please notify the sender and delete the original and any copies of this e-mail and any printouts immediately from your system and destroy all copies of it.



On 26 Feb 2024, at 23:32, Claudio Benghi ***@***.***> wrote:

﻿

EXTERNE-EMAIL Bitte klicken Sie nicht auf Links oder öffnen Sie keine Anhänge! Es sei denn, Sie kennen den Absender und wissen, dass der Inhalt sicher ist.

Hi Nick, are you suggesting to add documentation inside the XSD or in the markdown documents?

**Comment by atomczak** [comment]
Resolution: As URI interpretation does not affect the implementation of IDS checking, for the 1.0 version, we improved the markdown documentation. @CBenghi and @NickNisbet please review. 

We might add annotations in XSD for 1.1, but we would need to be consistent for other aspects like cardinality.
