### ISSUE TITLE
Attribute and Quantity as Independent Elements

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#25]
For more clearness and transparency we suggest a more explicit notation: We propose - without treat new concepts – a separate attribute and quantity element. Especially the actual attribute approach, we think, it’s inappropriate to modelling an attribute in form of a property (with the propertyset name "attribute") as suggested. This "secret code" is not transparent, and we avoid the approach that content controls the model structure. It could be a pragmatic approach in an established structure which is difficult to change but not in a new draft.

It could take a long time till IFC 5 is established. We think it is justified to use a concept for the moment that can be easily changed later.

We propose an independent attribute element which is very near to the property element. Our proposal is this quite analog to the property element:

```
     <ids:attribute location="…" uri="…" use="…">
          <ids:name … />
          <ids:value … />
     </ids:attribute>
```

In the same sense an additional and independent quantity element:

```
   <ids:quantity location="…" uri="…" use="…">
       <ids:quantityset>
           <ids:simpleValue>...</ids:simpleValue>|<xs:restriction>...</xs:restriction>
       </ids:quantityset>
       <ids:name … />
       <ids:value … />
   </ids:quantity>
```

**Comment by MatthiasWeise** [comment]
Proposal will make the specification more clear, see also #18

**Comment by berlotti** [comment]
processed. 

Parked the quantities discussion until decisions on units/measures have been made.
