### ISSUE TITLE
IDS schema location

### ISSUE THREAD

**Issue by mschro3der** [buildingSMART/IDS#250]
## What
- The schema location: [0.9.6](http://standards.buildingsmart.org/IDS/0.9.6/ids.xsd) known to me provides the schema via an html body tag (meta data: `<meta http-equiv="content-type" content="text/html; charset=windows-1252">`). 
- I would have expected that the schema is provided like: [inspire](https://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd). Here the schema file is directly available - which in my view is necessary for the usual tools to validate an xml file.

## Solution
- provide the plain schema file (and no html document of type `text/html`)

## Workaround
- link the current XSD from the github directory: [raw xsd](https://raw.githubusercontent.com/buildingSMART/IDS/master/Development/ids.xsd)

**Comment by CBenghi** [comment]
Hey @berlotti,

this has to do with the configuration of buildingSMART's webserver.

The suggested workaround could do, but would you be happy if we kept the official xsd files on github?
This would also allow us to work on beta versions of 1.1 more independently, retaining schema in various editors.

IDS files would change from:

```
xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/0.9.7/ids.xsd"
```
to
```
xsi:schemaLocation="http://standards.buildingsmart.org/IDS https://raw.githubusercontent.com/buildingSMART/IDS/master/Schema/1.0/ids.xsd"
```

**Comment by NickNisbet** [comment]
GitHub is not the place to hold official releases of buildingsmart standards. Stuff on GitHub can  be lost amongst official  working, rival, deprecated versions.

Sent whilst away from my desk.

Regards,

Nick.

Nicholas Nisbet FRSA MA(Cantab) DipArch(UNL)
Fellow:                              Royal Society of Arts
Fellow:                                buildingSMART International & UKI Chapter
Director:                            AEC3 UK Ltd
Web:                                   http://www.aec3.com<http://www.aec3.com/>
E-mail:                                ***@***.******@***.***>
Direct:                                +44 (0) 1494 714 933
Mobile:                              +44 (0) 781 616 8554
Registered Address:       46 St Margaret's Grove, Great Kingshill, High Wycombe, Bucks, HP15 6HP, UK

Vice-Chair:                     buildingSMART UK Chapter
Convenor:                       buildingSMART Regulatory Room

********** Confidentiality Notice **********.
This e-mail and any file(s) transmitted with it, is intended for the exclusive use by the person(s) mentioned above as recipient(s). This e-mail may contain confidential information and/or information protected by intellectual property rights or other rights. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution, copying, or action taken in relation to the contents of and attachments to this e-mail is strictly prohibited and may be unlawful. If you have received this e-mail in error, please notify the sender and delete the original and any copies of this e-mail and any printouts immediately from your system and destroy all copies of it.



On 26 Feb 2024, at 23:30, Claudio Benghi ***@***.***> wrote:

﻿

EXTERNE-EMAIL Bitte klicken Sie nicht auf Links oder öffnen Sie keine Anhänge! Es sei denn, Sie kennen den Absender und wissen, dass der Inhalt sicher ist.

Hey @berlotti<https://github.com/berlotti>,

this has to do with the configuration of buildingSMART's webserver.

The suggested workaround could do, but would you be happy if we kept the official xsd files on github?
This would also allow us to work on beta versions of 1.1 more independently, retaining schema in various editors.

IDS files would change from:

xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/0.9.7/ids.xsd"


to

xsi:schemaLocation="http://standards.buildingsmart.org/IDS https://raw.githubusercontent.com/buildingSMART/IDS/master/Schema/1.0/ids.xsd"

**Comment by MatthiasWeise** [comment]
Same issue with the new 0.9.7: https://standards.buildingsmart.org/IDS/0.9.7/ids.xsd
Any plans to fix?

**Comment by CBenghi** [comment]
For context, [according to documentation](https://www.rfc-editor.org/rfc/rfc3023), the ideal `content-type` returned by the server for the xsd files, should be `application/xml`.

**Comment by andyward** [comment]
Looks like it's an Apache server from the headers. Presumably whoever published the xsd content can finds someone to update the apache.config? I'd guess it just needs this adding to the httpd.config:

`AddType application/xml .xsd`

See https://httpd.apache.org/docs/2.4/mod/mod_mime.html#addtype

**Comment by atomczak** [comment]
The 'Content-Type' header has just been added, with the type: 'text/xml' (not 'application/xml' to include textual implementers agreements). Please test if it works now.

**Comment by mschro3der** [comment]
@atomczak Now also works via the web interface. Great!

Issue can therefore be closed.
