### ISSUE TITLE
Documentation checks

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#252]
- [ ] We should add a note to explain the limited LOIN support to the documentation for 1.0, see #232

**Comment by atomczak** [comment]
Made the documentation of IDS Purpose and Milestone aligned with Purpose (5.2) and Milestone (5.3) of LOIN standard. Our documentation does not mention the standard to keep IDS universal. I think an explanation of how IDS can support LOIN in practice could be an external article instead.
