### ISSUE TITLE
Remove the outdated "implementation agreement" comment lines from the schema

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/IDS#256]
The lines starting from here should be removed, since they're outdated. https://github.com/buildingSMART/IDS/blob/master/Development/ids.xsd#L67

Here are still the lines, if the line number mentioned above doesn't work due to changes to the file:
```
		<!-- Please note there is an implementation agreement on the use of minOccurs and maxOccurs.
			Valid values are: 
			a. 0 to unbounded, meaning Optional
			b. 1 to unbounded, meaning Required
			c. 0 to 0, meaning Prohibited
		 -->
```

**Comment by pasi-paasiala** [comment]
Also the first line:
```
<!-- Draft - Do not use in production -->
```
should be removed.

**Comment by CBenghi** [comment]
Hi @pasi-paasiala,
we will remove when freezing and updating the version number. Is that ok?

**Comment by CBenghi** [comment]
> The lines starting from here should be removed, since they're outdated. https://github.com/buildingSMART/IDS/blob/master/Development/ids.xsd#L67

I think the comment is valid, and relevant.

**Comment by pasi-paasiala** [comment]
> > The lines starting from here should be removed, since they're outdated. https://github.com/buildingSMART/IDS/blob/master/Development/ids.xsd#L67
> 
> I think the comment is valid, and relevant.

True. I didn't realize that this was a recent change.

**Comment by berlotti** [comment]
fixed
