### ISSUE TITLE
Arrangement of the Basic Elements

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#26]
A more stylistic point regards the arrangement of the basic elements: We propose to put the info element on top of the xml. From our point of view info element has a header character, so it belongs to the top. 

And we propose to bind together the specification elements in a collection list with a specifications (with -s!) element. In our experience is more common model style in xml files as an "open" list mixed with other xml elements (info and introductions).

So, the xml structure would look like this:

```
    <ids …>
        <info … />
        <specifications>
            <specification … />
            …
            <specification … />
        </specifications>
        <instructions … />
    </ids> 
```

Instead of IDS 0.4.2:

```
    <ids …>
        <specification … />
        …
        <specification … />
        <instructions … />
        <info … />
    </ids>
```

**Comment by berlotti** [comment]
Processed in 0.5.0
