### ISSUE TITLE
Inconsistent ifcVersion in IDS testcases 

### ISSUE THREAD

**Issue by andyward** [buildingSMART/IDS#273]
Most of the testcases in the [IDS folder](https://github.com/buildingSMART/IDS/tree/development/Documentation/testcases/ids) (10 out of 12 in development) seem to have an ifcVersion inconsistent with their corresponding test IFC file. i.e. they have an _ifcVersion="IFC2X3"_ in the IDS specification, but a _FILE_SCHEMA('IFC4')_ in the IFC. In all other testcases IFC4 is used consistently.

I'm assuming it's an oversight - apart from for _pass-specification_version_is_purely_metadata_and_does_not_impact_pass_or_fail_result.ids_

More generally, what is the thinking on the use of _ifcVersion_ during model validation? Looking at i[ds/pass-specification_version_is_purely_metadata_and_does_not_impact_pass_or_fail_result.ids](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/ids/pass-specification_version_is_purely_metadata_and_does_not_impact_pass_or_fail_result.ids) it seems that it should be ignored in terms of the test outcome?  

It feels like it would be appropriate to at least warn the user the model may not be compatible with the specification, given the spec may be written to account for schema-specific concepts?

**Comment by CBenghi** [comment]
Unfortunately, I still don't have an implementation of verification engine to spot these issues.

My view is that the IFC schema version should be considered. 
Indeed I think that wee need a richer regression suite that include such test cases, including pass and fail tests.

A PR is welcome if you can help.

**Comment by andyward** [comment]
Thanks Claudio. I've put a PR in for these IDS files. It's mainly just to avoid confusion amongst implementors over what the test case is testing.

I've also finally made our xbim IDS verification engine public at https://github.com/xBimTeam/Xbim.IDS.Validator - will update the implementors links via another PR, as this should be a pretty comprehensive & robust IDS 0.97 /1.0 implementation for anyone using Microsoft .NET (including cross platform Core support)

**Comment by CBenghi** [comment]
Thanks @andyward,
I will have to update the `scripts.md` file, because IDS files are generated, then accept the PR.
