### ISSUE TITLE
Classification System Parameter

### ISSUE THREAD

**Issue by VitalijTetervov** [buildingSMART/IDS#275]
Classification System parameter is identified as required in Documentation, yet BIMcert Handbook 2024 Edition in chapter 3.7.4 states that it is optional. Which one is correct?

![Classification system git](https://github.com/buildingSMART/IDS/assets/47089424/dc6e648a-caa3-4044-a9ae-e3a00016e7d5)
![Classification system](https://github.com/buildingSMART/IDS/assets/47089424/4cff8871-bbf2-4432-bb5c-953b45ba45af)

**Comment by kurb70** [comment]
Things are still in motion. The BIMcert manual refers to version 0.9.6 (see "3.7.1 Data structure" on page 124). At that time, this was still optional. It was only changed with 0.9.7.

I would expect additional changes until the first 1.0 version.

**Comment by kurb70** [comment]
BTW The manual for free: https://repositum.tuwien.at/handle/20.500.12708/192611

**Comment by CBenghi** [comment]
Closing because not related to this repository.
