### ISSUE TITLE
Schema mismatch in test case fail-a_specification_passes_only_if_all_requirements_pass_1_2

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#281]
The IFC file uses IFC4 schema, the IDS file uses IFC2X3, going by the name of the test case I don't think the intention is to fail on the schema mismatch. This is in the development branch.

https://github.com/buildingSMART/IDS/blob/development/Documentation/testcases/ids/fail-a_specification_passes_only_if_all_requirements_pass_1_2.ids

https://github.com/buildingSMART/IDS/blob/development/Documentation/testcases/ids/fail-a_specification_passes_only_if_all_requirements_pass_1_2.ifc

**Comment by rubendel** [comment]
The same seems to be the case for many of the test cases in the "ids" folder.

**Comment by andyward** [comment]
I think this may be a duplicate of #273. There's an open PR to fix (#276)

**Comment by rubendel** [comment]
Ah yes you are right, missed that one, I'll close this one.
