### ISSUE TITLE
Default branch settings

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#293]
Hello @berlotti,

Would it be ok to change the repo settings so that 'development' is the default branch?
This would allow for some github automation (e.g. closing issues on successful merge).

If so, you'll have to do it, because I don't have admin privileges.
Of course we would still merge to `master` and tag the commit on release versions.

Thanks

**Comment by berlotti** [comment]
Done. 
Just be aware of the open pull requests on 'master'!
