### ISSUE TITLE
Data type of IfcLengthMeasure "Real" or "Double"?

### ISSUE THREAD

**Issue by vitorhpmartins** [buildingSMART/IDS#295]
double of IDS = https://github.com/buildingSMART/IDS/blame/6893df1669755263b2362b82752092d9c64a6e5e/Documentation/DataTypes.md#L191

real of IFC = https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcLengthMeasure.htm

Why does the IDS specification list the type of, for example, IfcLengthMeasure as a 'double' type, whereas the official documentation of Ifc lists it as a 'real' type for the same property?

![image](https://github.com/buildingSMART/IDS/assets/116745805/3001da6d-757d-4617-b28c-32f8112034fd)

Isn't the purpose of IDS to validate Ifc files? Shouldn't the data types be in the same data structure?

Why am I asking this question? Because for normal users (non-programming users), it can be confusing to create a BIM Execution Plan (BEP) with the required Level of Information Needed if the documentation in each location (IDS and IFC) is different.

**Comment by aothms** [comment]
For practical purposes considered, this is the same (or closest equivalent) in both modelling languages. Given the desire to reuse common modelling practices, we decided to map to the existing terms.

A bit more technical write up follows below:

XSD numeric types:

> ![xsch_0403](https://github.com/buildingSMART/IDS/assets/1096535/b47e6445-78d3-47fe-b84a-2ceabda44391)
> 
> Source: https://docstore.mik.ua/orelly/xml/schema/ch04_04.htm

Express numeric types:

> `number`
> &nbsp; └ `integer`
> &nbsp; └ `real`


When mapping between the modeling languages the following characteristics of number types can be taken into account, and as such you can see that there is no perfect answer. We could consider defining our own number type called `ids:real` to prevent this naming confusion as observed by @vitorhpmartins and more precisely match the semantics (in particular to disallow non-finite items, one could write an IDS now saying a value need to be infinite, which can never be realized in IFC, but luckily we have the IDS validator in addition to plain XSD validation).

### Allows non-finite items (nan, inf):

`xs:float` `xs:double`

### Arbitrary unbounded precision

`express:real` `xs:decimal`

### Allows for exponential notation

`express:real` `xs:float` `xs:double`
