### ISSUE TITLE
List of datatypes with Enum types used by attributes

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/IDS#296]
Why do we list enumeration types like IfcBeamTypeEnum in the list for Property dataTypes?
https://github.com/buildingSMART/IDS/blob/6893df1669755263b2362b82752092d9c64a6e5e/Documentation/DataTypes.md

My understanding is that these datatypes are used by schema attributes only (PredefinedType of IfcBeam etc.). The datatype does not have to be provided for attributes and, to my understanding, cannot be used by properties. If we list enum for properties, I would maybe expect definitions used by existing Psets like PEnum_ElementStatus, although I would rather go with the base datatype like IfcLabel.

**Comment by CBenghi** [comment]
I understand... the underlying type of enums is an actual IFCLABEL in the IFC file... while the 'template' is coming from the enumeration type.
I will see to improve the tool and the documentation appropriately.

**Comment by SergejMuhic** [comment]
The underlying type of property enums is an `IfcLabel` not of enums. Enums are EXPRESS ENUMERATION types. Those two are not to be confused. Property enums were serialized as a computer interpretable listing in .ifc and .ifcxml as declared in a project library. This was not done in 4.3.2 for whatever reason.

Enums (not property) are part of the EXPRESS schema. They are not IfcLabel in ifc file and also not parsed as such. IfcLabel is enclosed in single quotes and enums in dots ('' vs ..).

**Comment by aothms** [comment]
> This was not done in 4.3.2 for whatever reason.

It's not heavily advertised / published, but it does exist. Just fyi.

`#4916=IFCPROPERTYENUMERATION('PEnum_TankAccessType',(IFCLABEL('LOOSECOVER'),IFCLABEL('MANHOLE'),IFCLABEL('NONE'),IFCLABEL('SECUREDCOVER'),IFCLABEL('SECUREDCOVERWITHMANHOLE'),IFCLABEL('OTHER'),IFCLABEL('NOTKNOWN'),IFCLABEL('UNSET')),$);`

https://github.com/buildingSMART/IFC4.3.x-output/blob/master/Pset_IFC4X3.ifc#L4923

**Comment by SergejMuhic** [comment]
Oh, my we could have used this last month! 😄

**Comment by Moult** [comment]
I think most BBIM users also heavily use custom pset template definitions with property enumeration. So it's pretty common here :)

**Comment by berlotti** [comment]
would be nice to add to IDS Audit tool? @CBenghi
