### ISSUE TITLE
IMPROVEMENT: functionality to point towards bSDD (data dictionaries)

### ISSUE THREAD

**Issue by lfcastel** [buildingSMART/IDS#299]
Taking this image, where enumerations are hard coded into the xml, should there not be a possibility to just point towards data dictionaries (e.g. bSDD) where these values are hosted? IDS generating applications could of course also connect to data dictionaries and automatically encode them into the ids.. Not sure what is best..
![image](https://github.com/buildingSMART/IDS/assets/73949503/1bab92fd-114d-4bf8-9c13-3e7711087b60)

**Comment by berlotti** [comment]
That would create a dependency on an external system.
Dependency on external systems is the kind of thing we don't want at buildingSMART. 
It is actually the main reason we exist.

**Comment by lfcastel** [comment]
> That would create a dependency on an external system. Dependency on external systems is the kind of thing we don't want at buildingSMART. It is actually the main reason we exist.

Well, it could be an optional way of specifying, so then there is no (real) dependency. Furthermore, that external system could be bSDD, which is your own system. Data dictionaries are about connecting distributed (external) information sources, which is what you are doing with bSDD so I do not understand your answer tbh. Anyway, it was just an idea... no worries if it's not on the roadmap :)

**Comment by atomczak** [comment]
It doesn't hurt to have a long list of enumerations in IDS. As you noted, the IDS authoring software can actually make such a list based on bSDD. The reason it is explicit is to have enough information in an IDS to be able to perform IFCxIDS checking locally.

In IDS there is a place to reference bSDD definitions (the URI attribute of Property, Material and Classification requirement facets). But it doesn't need to be from bSDD, and IDS implementers don't need to implement bSDD API.

**Comment by lfcastel** [comment]
OK fair enough Artur! :) Thanks for the answer!
