### ISSUE TITLE
Model completeness

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#3]
Hello,

Is there a document where I may read about the aim of this format?
I'm particularly interested in its scope.

I assume that checks that go beyond information availability are (at least at this stage) out of scope.

But, are we expecting that there should be methods for specifying model completeness?

I'm thinking for example of rules such as:

- at least one boiler per building
- one handrail per ramp
- some predetermined number of ifcFlowTerminalTypes
- some predetermined number of ifcWallTypes with a minimum number of wall instances each

Thanks,
Claudio

**Comment by berlotti** [comment]
This project is creating a 'language' to define 'Information Delivery Specifications'. There are many examples of IDSs in practise. These will be used to guide scope and focus.
This project explicitly does not want to create a language for design- or requirements validation. e-Permit examples like 'rooms above 3m should contain fire detectors within 1m of the door’ are out of scope. In scope are requirements like 'we need rooms' and 'fire detectors need to be delivered as IfcSensor, with predefined type x, and Pset_SensorTypeSmokeSensor'. Design validation rules are a differen topic from information delivery specifications.
