### ISSUE TITLE
userdefuned

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#308]
`entity\pass-userdefuned_predefined_types_may_be_specified.ids`

should probably be named

`entity\pass-userdefined_predefined_types_may_be_specified.ids`

**Comment by CBenghi** [comment]
Quite right, I'll address that, apologies.

**Comment by enzoaggazioALMA** [comment]
The ids file in test case is probably wrong, the tag:
 ```
 <predefinedType>
            <simpleValue>USERDEFINED</simpleValue>
 </predefinedType>
 ```

must be replaced with:

 ```
 <predefinedType>
            <simpleValue>WALDO</simpleValue>
 </predefinedType>
 ```

**Comment by andyward** [comment]
> The ids file in test case is probably wrong, the tag:
> 
> ```
> <predefinedType>
>            <simpleValue>USERDEFINED</simpleValue>
> </predefinedType>
> ```
> 
> must be replaced with:
> 
> ```
> <predefinedType>
>            <simpleValue>WALDO</simpleValue>
> </predefinedType>
> ```

I think the test is right. What's the requirement is trying to test is that the entities have a PreDefinedType of USERDEFINED - but we don't want to check the specific user-defined type provided in ObjectType/ElementType etc.

i.e. we're checking for `.USERDEFINED.` not `WALDO`
![image](https://github.com/buildingSMART/IDS/assets/923699/ea903fcc-b1b5-4876-8220-f0578f4bd9d9)

There are separate test cases that test for checking specific User Defined Type values etc. e.g. _pass-a_predefined_type_may_specify_a_user_defined_object_type.ids_ and _fail-user_defined_types_are_checked_case_sensitively.ids_

**Comment by berlotti** [comment]
We are trying to move away from user-defined types (and in IFC 5 even from predefined-types). 
Best practise is to use/add a classificationreference to the IFC class to further specify it. 
The best-practise guidelines for IDS might change in 1.1 to reflect this movement.

**Comment by enzoaggazioALMA** [comment]
To check the predefined type attribute, we could test this way:

```
 <requirements>
        <attribute>
          <name>
            <simpleValue>PredefinedType</simpleValue>
          </name>
          <value>
            <simpleValue>WALDO</simpleValue>
          </value>
        </attribute>
      </requirements>
```

**Comment by andyward** [comment]
> Best practise is to use/add a classificationreference to the IFC class to further specify it.
Agreed - When everything is classified that's where Classification Facets come in of course.


@enzoaggazioALMA 
> To check the predefined type attribute, we could test this way:
> [using an attribute facet]
Presumably with :
```xml
...
<value>
   <simpleValue>UNDEFINED</simpleValue> <!-- rather than WALDO-->
</value>
```
While this may work, it's worth noting that I believe the Entity Predefined Type logic should check the DefiningType as well as the instance. So for instance in IFC2x3 an IFCWALL has no PredefinedType - it's on the IFCWALLTYPE. So you may get subtle differences accessing via Attribute facet
