### ISSUE TITLE
Test case naming consistency

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#309]
Many of the new IDS test cases (mostly the ones in the tolerance folder) do not conform to the earlier used naming convention of using either the "pass-" or "fail-" prefix, many of them are now prefixed with either "pass_" or "fail_".

**Comment by CBenghi** [comment]
There might have been a bit of a rush from Leon in the merging of PRs yesterday.
I'm going to review this asap, but I'm unfortunately caught up on a different deadline for a few days.

**Comment by atomczak** [comment]
Apologies, my bad. Fixed them in the commits ~~above~~below.
