### ISSUE TITLE
2 testcases have .html file instead of .ifc

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#310]
The following two test cases have a .html file instead of a .ifc file.

`property\pass-floating_point_numbers_are_compared_with_a_1e_6_tolerance_1_4`
`property\pass-floating_point_numbers_are_compared_with_a_1e_6_tolerance_2_4`

**Comment by andyward** [comment]
Looks to me that these 2 tests should be deleted since the more comprehensive Floating point tests are now in the tolerance folder.

**Comment by atomczak** [comment]
Apologies, my bad; missed the two tests while implementing tolerance tests at the last minute.
