### ISSUE TITLE
Tolerance documentation 1.0.0

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#311]
With https://github.com/buildingSMART/IDS/pull/294 closed and IDS version now at 1.0.0, can we assume the documentation to be final? https://github.com/buildingSMART/IDS/blob/development/Documentation/developer-guide.md#precision

With this implemented I am getting quite a lot of failed test cases

**Comment by aothms** [comment]
I think #294 wasn't supposed to be closed. The bit of documentation you referenced misses the `abs()` part, so doesn't properly handle negative values. See https://github.com/buildingSMART/IDS/blob/0d50fd8f2dbd5b388f6fafb67da255cc3ce2b4ca/Documentation/tolerance.md

**Comment by CBenghi** [comment]
Hello Ruben,
not quite yet, the vote held by the panel ratified the schema.
We are still working with the IDS development group to complete the test case documentation.
My personal view is that this will eventually result in a robust implementation across all platform, and I hope that a certification process will guarantee such coherence for all implementers.
I'm hoping to complete this step before the end of the month. I welcome all feedback on test-cases and I'm available for any conversation or one-to-one that might help implementers.
Best,
Claudio

**Comment by berlotti** [comment]
The issue closed automatically when merging the pull request. 
Had to process all PRs due to the change in default branche. 
Let's indeed take some time to properly document this (and update Audit tool as well)

**Comment by rubendel** [comment]
@aothms Ah thanks Thomas, I did see a reference to the mentioned document, but it does not exist in the development branch. Nice work, don't understand much of math symbols, but adding `abs` I can :). @CBenghi Ok that's clear, I'll report whatever I find.

**Comment by giuseppeverduciALMA** [comment]
@rubendel sorry, by mistake, I closed this PR while synchronizing the IDS repository... 
@CBenghi, could you directly add the file on the development branch?

**Comment by atomczak** [comment]
The tolerance.md file is now added to the development (#317).

**Comment by atomczak** [comment]
please confirm if this can be closed now @rubendel @CBenghi
