### ISSUE TITLE
Broken links on dev Readme

### ISSUE THREAD

**Issue by petrisch** [buildingSMART/IDS#327]
The links in https://github.com/buildingSMART/IDS/tree/v1.0.0/Documentation
that point to:

https://github.com/buildingSMART/IDS/blob/v1.0.0/Documentation/library/sample.ids
https://github.com/buildingSMART/IDS/blob/v1.0.0/Documentation/library/sample.ifc

are broken. I guess they should point to a file in the Developement folder now,
but I'm not sure which one should be the "entry point".

**Comment by VitalijTetervov** [comment]
This is still an issue. It would be great to have a file for testing :)
