### ISSUE TITLE
Add textual definitions to each IDS element 

### ISSUE THREAD

**Issue by mickbaggen** [buildingSMART/IDS#328]
The IDS documentation and XSD do not contain unambiguous textual definitions of the IDS elements, such as specification, requirement, facet etc. Please add a textual definition for each element, in the style of "a requirement is a <supertype> which is <discriminating characteristic>".

**Comment by berlotti** [comment]
You can find those in IDS under 'instructions' and 'description'.

**Comment by atomczak** [comment]
If that's about the explanation of what it means in the standard, we do have it in the docs and let's keep the schema lean:
https://github.com/buildingSMART/IDS/blob/development/Documentation/specifications.md
https://github.com/buildingSMART/IDS/blob/development/Documentation/attribute-facet.md etc.
