### ISSUE TITLE
IDS master branch has disappeared

### ISSUE THREAD

**Issue by andyward** [buildingSMART/IDS#333]
The IDS _master_ branch seem to have disappeared in Github. The default is now _development_ but that has a number of changes since the official 1.0 release (which was at 1effec6f419798ce09617416d258a35bdc58320a).

Just checking this is correct and intended - as it means anyone access the repo may be getting a slightly different version of things (mainly slightly updated tests by the look of things).

**Comment by atomczak** [comment]
I looked into logs, and it seems that 'development' has been the default branch since 9th March 2024. However, I don't see the action of deleting 'master'. Perhaps it was renamed instead?
[export-buildingSMART-1723289502.json](https://github.com/user-attachments/files/16569398/export-buildingSMART-1723289502.json)

> {"@timestamp":1715294608611,"_document_id":"yNa_HMfkFaPnXtwnX_ZhzA","action":"repo.update_default_branch","actor":"berlotti","actor_id":356921,"actor_is_bot":false,"changes":{"default_branch":"development","old_default_branch":"master"},"created_at":1715294608611,"operation_type":"modify","org":"buildingSMART","org_id":5180517,"public_repo":true,"repo":"buildingSMART/IDS","repo_id":242965765,"user_agent":"Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","visibility":"public"}

**Comment by jbrouwerdigibase** [comment]
Maybe next to a main/master also add a major version branch like 1.x?

**Comment by CBenghi** [comment]
I have a local copy of master with the following as latest commit: 

```
Author: Léon van Berlo <github@berlotti.com>
Date: 03/06/2024 10:39:23
Committer: GitHub <noreply@github.com>
Commit hash: 6a308a85f6178b246c5df89eb2b6f6f5d8485e50

Update ids.xsd
```

Is there anybody with later content?

**Comment by berlotti** [comment]
It was renamed on the request of @CBenghi  
https://github.com/buildingSMART/IDS/issues/293

**Comment by CBenghi** [comment]
Hi Leon,
That's not the case.
That issue is about changing the default branch in the settings, which is a
different matter of the one we are discussing here.
The master and development branches were not renamed, AFAIK.
Best,
Claudio

**Comment by atomczak** [comment]
as discussed on a call, the development is most up to date and 'master' is only a name. Perhaps a good moment to no longer have master/development but rethink our branch policy. Please provide feedback in #335.

**Comment by andyward** [comment]
> I have a local copy of master with the following as latest commit:
> 
> ```
> Author: Léon van Berlo <github@berlotti.com>
> Date: 03/06/2024 10:39:23
> Committer: GitHub <noreply@github.com>
> Commit hash: 6a308a85f6178b246c5df89eb2b6f6f5d8485e50
> 
> Update ids.xsd
> ```
> 
> Is there anybody with later content?

Sorry - been away.

@CBenghi My fork showed a few more commits after that. See https://github.com/andyward/IDS/commits/master/

I think was where we were at when master got removed - and it looks like we're not missing anything from the development branch.

**Comment by andyward** [comment]
Closing as this seems to have been resolved / by design. We have a 1.0 tag (albeit we should probably tag a 1.0.1 release as of 7171c00871b29ce56e667e7669f926c1a1d7f0da - which includes [21 commits](https://github.com/buildingSMART/IDS/compare/v1.0.0...andyward:IDS:master) after the 1.0  tag with updates to the latest 1.0 Test cases & docs)
