### ISSUE TITLE
Documentation Readme references missing example/sample files

### ISSUE THREAD

**Issue by andyward** [buildingSMART/IDS#334]
The latest Documentation readme at https://github.com/buildingSMART/IDS/blob/development/Documentation/README.md has broken links under the Beginners Tutorial section where the sample files link to:

* /Documentation/library/sample.ids
* /Documentation/library/sample.ifc

These files do not exist at this path, and I could not find them elsewhere in the repository.

**Comment by atomczak** [comment]
repeats #327
