### ISSUE TITLE
Interpretation of values

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#34]
Hello,

We have a working implementation of IDS version 0.5, but I'm having trouble to understand the following lines.

https://github.com/buildingSMART/IDS/blob/7903eae20127c10b52cd37abf42a7cd7c2bcf973/Development/0.5/IDS_random_example_04.xml#L12-L18

Is this by design?
Thanks,
Claudio

**Comment by berlotti** [comment]
This is probably invalid combination of restrictions. See #20

**Comment by CBenghi** [comment]
Ah, thanks. 
I had missed that conversation.
