### ISSUE TITLE
PartOf Examples

### ISSUE THREAD

**Issue by VitalijTetervov** [buildingSMART/IDS#358]
The last example describing window in PartOf Facet table (https://github.com/buildingSMART/IDS/blob/development/Documentation/UserManual/partof-facet.md) is incorrect.

Applicability Intention
Current: Any window that hosted by a hand wash basin
Possibly change to: Any window that is hosted by a wall

Requirement Intention
Current: The entity (e.g. faucet) must be fixed on a hand wash basin
Possibly change to: A window must be nested in the wall

Facet Definition
Current: Relation="IFCRELNESTS", Entity="IFCSANITARYTERMINAL"
Possibly change to: Relation="IFCRELNESTS", Entity="IFCWALL"

**Comment by atomczak** [comment]
Nice catch! Actually, the last two rows are duplicated, but only the second mentions wall. I will remove that row, leaving the example with the hand wash basin as it is (just improving the grammar).
