### ISSUE TITLE
IfcBoolean verification error

### ISSUE THREAD

**Issue by Miyate2** [buildingSMART/IDS#361]
Description:
I found a bug in ifcTester's Boolean value validation functionality. The validator incorrectly passes validation even when Boolean values don't match.

Steps to Reproduce:
1. Created an IFC file with the following properties:
   - Entity: IFCMEMBER
   - Pset: Pset_MemberCommon
   - BaseName: IsExternal
   - Value (Boolean): true
   - DataType: IFCBOOLEAN

2. Created an IDS with the following requirements:
   - Entity: IFCMEMBER
   - Pset: Pset_MemberCommon
   - BaseName: IsExternal
   - Value (Boolean): false
   - DataType: IFCBOOLEAN

3. Ran validation using ifcTester

Current Behavior:
The validation passes despite the IsExternal values being different (true vs false).

Expected Behavior:
The validation should fail when Boolean values don't match between IFC and IDS.

Request:
Please modify facet.py in ifcTester to properly validate IfcBoolean values.

**Comment by andyward** [comment]
@Miyate2 You'd be better off logging over at https://github.com/IfcOpenShell/IfcOpenShell/labels/IfcTester
