### ISSUE TITLE
Breaking symmetry for partOf

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#38]
Hello,

If I read the schema correctly, the introduction of `partOf` in 9f85b90cb976613910162890c216c3fcc2259431 seems to break the symmetry of facets between applicability and requirement.

https://github.com/buildingSMART/IDS/blob/9f85b90cb976613910162890c216c3fcc2259431/Development/0.5/ids_05.xsd#L192-L210

I don't have a strong opposition to this, but my spider sense goes tingling to the roof whenever something like this happens.
What is the point of excluding this feature (if useful) from applicability?

I though symmetry of facets was an important aspect of IDS.

**Comment by berlotti** [comment]
Most of the facets in the requirements section have additional attributes.  See 'use' and 'use'. 
The partOf attribute was also added in the same way outside of the type.

<img width="584" alt="Screenshot 2022-01-26 at 11 57 00" src="https://user-images.githubusercontent.com/356921/151151334-62a3378b-51bc-40f8-994f-d4718a4a5ebd.png">

**Comment by CBenghi** [comment]
I see, I missed a couple of meetings, sorry.
For implementation purposes, retaining the symmetry would make life easier, of course.
It might also help users in the perception of the schema.

Why have we excluded that we can use partOf as criterion for applicability?

**Comment by berlotti** [comment]
We didn't see any example that need 'PartOf' as applicability. 
It could be added in later versions when practical use shows it is required.
