### ISSUE TITLE
Nature of the examples

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#4]
Hello @berlotti,

reading through the examples I don't understand if they are to be considered alternative ideas or both valid.

https://github.com/buildingSMART/IDS/blob/07b5d32b1996260c56265f35fbed63bcf24c251a/examples/Wall/json-schema_wall_example.json#L2

Suggests the intention to use ```json-schema``` itself to specify the requirements, whereas 

https://github.com/buildingSMART/IDS/blob/07b5d32b1996260c56265f35fbed63bcf24c251a/examples/project%20and%20site%20properties/project_and_site_EIR.txt#L2

is an independent format.

Because the implementation screenshot uses the second I'm inclined to think that this would be the preferred plan. 

Could you clarify if they are intended to coexist?
Thanks,
Claudio

**Comment by berlotti** [comment]
Hi Claudio,

This repo was very experimental. The work was done as feasibility study. Based on the outcome of this work, and the research into excising initiatives, the official IDS project was started. 

The IDS project is collecting use cases and defining scope. Based on that work technology choices will be made.

**Comment by CBenghi** [comment]
Thanks Léon,
I'd like to participate in the work of this Project.
Is Cyrille Pennavaire the right person to contact for that?
Best,
Claudio

**Comment by berlotti** [comment]
Formally the project has not started yet.
It is collecting use-cases at
https://technical.buildingsmart.org/projects/information-delivery-specification-ids/
The best next step would be to upload real world data requirements on that
site.
