### ISSUE TITLE
Consolidation of IDS check results

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#42]
Currently IDS has the applicability phase where we select objects to check and the requirements phase where those objects are being checked. The nice thing about this is that when working with the results, you know which objects were checked, and which of those failed and which succeeded. Currently all results are based on the individual objects either passing or failing.

There are also use cases where one would like to put constraints on the amount of objects that failed or passed.

# Examples
1. **Can not use certain entities**
A typical requirement is to say that for example IfcBuildingProxyObject cannot be used at all. The applicability could be set to Entity IfcBuildingProxyObject, but there is no way to say that when at least one results comes up, it's a failure.

2. **Must use certain entities**
You can imagine that at least one IfcProject, one IfcSite and one IfcBuilding and perhaps one IfcBuildingStorey must be in the model. Some of these would obviously not even pass the IfcSchema validation, but others would.

3. **Properties on IfcProject**
You can imagine the need to check certain properties to exist on the IfcProject entity. You would probably put an Entity applicability on IfcProject and then a few properties in the requirements. But what if there is no IfcProject in the model at all? Would that mean it's valid? No it would not, and you should be able to indicate this in the IDS itself.

# Proposal
To extend the 2 existing phases with a 3rd (optional) phase: Consolidation (there is probably a better word for it). It can have multiple success or multiple error tags, but no mix of the two.
```xml
<consolidation>
  <success phase="applicability | requirements" when="NO_RESULTS | EXACTLY_ONE_RESULT | AT_LEAST_ONE_RESULT | MORE_THAN_ONE_RESULT" />
  <error phase="applicability | requirements" when="NO_RESULTS | EXACTLY_ONE_RESULT | AT_LEAST_ONE_RESULT | MORE_THAN_ONE_RESULT" />
</consolidation>
```
The idea is that this allows you to define what makes a single IDS specification fail or succeed. Assuming that the second phase (requirements) returns all objects that failed the requirements, the default would be:
```xml
<consolidation>
  <success phase="requirements" when="NO_RESULTS" />
</consolidation>
```

# Example implementations:

**Example 1**
Only the applicability phase is needed, and it cannot have any results. You can also define this check with an applicability of "all objects" and then add an entity requirement of IfcBuildingElementProxy (in that case the phase needs to be "requirements".
```xml
<consolidation>
  <success phase="applicability" when="NO_RESULTS" />
</consolidation>
```

**Example 2**
Assuming that one specification is created for each entity that needs to be checked. No requirements are needed for this check, and the applicability phase should result in at least one (or exactly one for some) result.
```xml
<consolidation>
  <success phase="applicability" when="AT_LEAST_ONE_RESULT" />
</consolidation>
```

**Example 3**
There must be exactly one IfcProject (applicability phase should result in 1 object), and there can be no results (failures) of the requirements phase:
```xml
<consolidation>
  <success phase="applicability" when="EXACTLY_ONE_RESULT" />
  <success phase="requirements" when="NO_RESULTS" />
</consolidation>
```

**Comment by atomczak** [comment]
as discussed in today's meeting, the `use` attribute support the case when you need at least one instance of an object matching the applicability to be present in the model:
`<ids:specification ifcVersion="IFC2X3" name="Stijlen en Dorpels" use="required">`

I don't see a need to have a certain number of elements, like 'there should be at least 4 walls'.

> Can not use certain entities
> A typical requirement is to say that for example IfcBuildingProxyObject cannot be used at all. The applicability could be set to Entity IfcBuildingProxyObject, but there is no way to say that when at least one result comes up, it's a failure.

This I think we can't do with the current schema, and it might be useful. How about adding a third option to the `use` attribute: "forbidden"?
