### ISSUE TITLE
Example regex does not seem to be a valid regex

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#43]
https://github.com/buildingSMART/IDS/blob/785424caf905739ab5c34322e2e4de5a0959f3bd/Development/0.5/Wooden%20windows/IDS_wooden-windows.xml#L187

**Comment by berlotti** [comment]
We couldn't agree on a regex flavor (#29 )
So that leaves us with the XSD:Pattern.
I think this is valid <xs:pattern> and that is indeed different from commonly known regex.

Link to #29  discussion.

**Comment by rubendel** [comment]
You are right, perfectly valid XSD:Pattern

**Comment by CBenghi** [comment]
Can't sleep tonight and I was looking at implementing the regex flavour... 

However I can't see how `*(glas)*` is a valid pattern.

If I look at https://www.w3.org/TR/xmlschema-2/#dt-regex, it still feels like the first quantifier would need to be attached to an atom according to the following spec

```
piece ::= atom quantifier?
```

What am I missing?

**Comment by aothms** [comment]
I tend to agree with @CBenghi . If the intent is to match a substring then it can be `.*glass.*`. This is different in XML patterns where the regex is implicitly anchored to begin and end, so the `.*` on both sides are necessary to do a substring match. If the intent is indeed to allow zero or more repetitions of the phrase `glass` such `glassglassglassglassglass`, then the regex can be `(glass)*`.

**Comment by berlotti** [comment]
yes. Thank you. Changed both the 'glas' and 'RAL' example.
