### ISSUE TITLE
Empty material should not be there

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#44]
https://github.com/buildingSMART/IDS/blob/785424caf905739ab5c34322e2e4de5a0959f3bd/Development/0.5/Wooden%20windows/IDS_wooden-windows.xml#L63

If might be an idea to make this invalid in the schema as well.

**Comment by berlotti** [comment]
In IDS this means it should have a material, but can be any value.

**Comment by rubendel** [comment]
Ok thanks
