### ISSUE TITLE
Interpretation of location for AttributeType

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#45]
Hello,
I'm not quite sure how to interpret the location clause for an attribute type.

https://github.com/buildingSMART/IDS/blob/ffbd3963fa36f1b0075ce6009d24bcd87de6afcf/Development/0.5/ids_05.xsd#L178-L186

I hope I get it right that this facet points, for instance, to an `IfcWindow.OverallHeight`.
If that's the case what does it mean to be specified at "type" level? 
`IfcWindowType` does not have that attribute, of course.

Is this just an oversight?
Thanks,
Claudio

**Comment by aothms** [comment]
But attribute such as Name is of course defined for both so I think
location makes some sense. Invalid attribute names will have to be checked
and reported. We also have to make a note that this should not be used to
constrain the predefinedtype. How complex values are handled such as
reflatitude on the site. Etc.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op di 8 feb. 2022 15:24 schreef Claudio Benghi ***@***.***>:

**Comment by CBenghi** [comment]
@aothms, you're right, I get it now.

It might actually be quite useful, on the applicability side.
e.g. `All windows of a given type name must have some constraint.`
I'll have to extend the helpers to include type attribute names.
