### ISSUE TITLE
Specification has no name

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#46]
https://github.com/buildingSMART/IDS/blob/ffbd3963fa36f1b0075ce6009d24bcd87de6afcf/Development/0.5/Wooden%20windows/IDS_wooden-windows.xml#L177

**Comment by rubendel** [comment]
I think it should be

**Comment by berlotti** [comment]
Agreed in the meeting. Will process. 

Documentation should motivate people to use unique names in an IDS file.

**Comment by atomczak** [comment]
Agree on having the name mandatory. 

I see a case where you might actually want to have duplicate names - when someone is not familiar with enumeration restriction, s/he might want to duplicate the clause and have results shown as if it was the same specification. There is always the possibility people don't use the tools as we would expect them to.
