### ISSUE TITLE
dimensional exponents

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#47]
Hello @berlotti,

I've spent a little time filling in the remaining dimensional exponents in the table from the wiki...
because I haven't got write permissions in the wiki, I'm pasting the markdown code here.

I hope it helps.

| Physical Quantity (unique name to be used in IDS)             | Unit         | Unit Symbol | Ifc Measure                          | dimensional exponents   | QUDT                                  |
| ----------------------------- | ------------ | ----------- | ------------------------------------ | ----------------------- | ------------------------------------- |
| Amount of substance           | mole         | mol         | IfcAmountOfSubstanceMeasure          | (0, 0, 0, 0, 0, 1, 0)   |                |
| Area density                  |              | Kg/m2       | IfcAreaDensityMeasure                | (-2, 1, 0, 0, 0, 0, 0)  | quantitykind:MassPerArea              |
| Area                          | square meter | m2          | IfcAreaMeasure                       | (2, 0, 0, 0, 0, 0, 0)   | quantitykind:Area                     |
| Dynamic viscosity             |              | Pa s        | IfcDynamicViscosityMeasure           | (-1, 1, -1, 0, 0, 0, 0) | quantitykind:DynamicViscosity         |
| Electric capacitance          | farad        | F           | IfcElectricCapacitanceMeasure        | (-2, 1, 4, 1, 0, 0, 0)  | quantitykind:Capacitance              |
| Electric charge               | coulomb      | C           | IfcElectricChargeMeasure             | (0, 0, 1, 1, 0, 0, 0)   | quantitykind:ElectricCharge           |
| Electric conductance          | siemens      | S           | IfcElectricConductanceMeasure        | (-2, -1, 3, 2, 0, 0, 0) | quantitykind:ElectricConductivity     |
| Electric current              | ampere       | A           | IfcElectricCurrentMeasure            | (0, 0, 0, 1, 0, 0, 0)   | quantitykind:ElectricCurrent          |
| Electric resistance           | ohm          | Ω           | IfcElectricResistanceMeasure         | (2, 1, -3, -2, 0, 0, 0) | quantitykind:Resistance               |
| Electric voltage              | volt         | V           | IfcElectricVoltageMeasure            | (2, 1, -3, -1, 0, 0, 0) | quantitykind:Voltage                  |
| Energy                        | joule        | J           | IfcEnergyMeasure                     | (2, 1, -2, 0, 0, 0, 0)  | quantitykind:Energy                   |
| Force                         | newton       | N           | IfcForceMeasure                      | (1, 1, -2, 0, 0, 0, 0)  | quantitykind:Force                    |
| Frequency                     | hertz        | Hz          | IfcFrequencyMeasure                  | (0, 0, -1, 0, 0, 0, 0)  | quantitykind:Frequency                |
| Heat flux density             |              | W/m2        | IfcHeatFluxDensityMeasure            | (0, 1, -3, 0, 0, 0, 0)  | quantitykind:HeatFluxDensity          |
| Heating                       |              | J/K         | IfcHeatingValueMeasure               | (2, 1, -2, 0, -1, 0, 0) | quantitykind:HeatCapacity             |
| Illuminance                   | lux          | lx          | IfcIlluminanceMeasure                | (-2, 0, 0, 0, 0, 0, 1)  | quantitykind:Illuminance              |
| Ion concentration measure     |              | Kg/m3       | IfcIonConcentrationMeasure           | (-3, 1, 0, 0, 0, 0, 0)  | quantitykind:IonDensity               |
| Iso thermal moisture capacity |              | m3/Kg       | IfcIsothermalMoistureCapacityMeasure | (3, -1, 0, 0, 0, 0, 0)  |                                       |
| Length                        | meter        | m           | IfcLengthMeasure                     | (1, 0, 0, 0, 0, 0, 0)   | quantitykind:Length                   |
| Speed                         |              | m/s         | IfcLinearVelocityMeasure             | (1, 0, -1, 0, 0, 0, 0)  | quantitykind:Speed                    |
| Luminous flux                 | Lumen        | lm          | IfcLuminousFluxMeasure               | (0, 0, 0, 0, 0, 0, 1)   | quantitykind:LuminousFlux             |
| Luminous intensity            | candela      | cd          | IfcLuminousIntensityMeasure          | (0, 0, 0, 0, 0, 0, 1)   | quantitykind:LuminousIntensity        |
| Mass density                  |              | Kg/m3       | IfcMassDensityMeasure                | (-3, 1, 0, 0, 0, 0, 0)  | quantitykind:MassDensity              |
| Mass flow rate                |              | Kg/s        | IfcMassFlowRateMeasure               | (0, 1, -1, 0, 0, 0, 0)  | quantitykind:MassFlowRate             |
| Mass                          | kilogram     | Kg          | IfcMassMeasure                       | (0, 1, 0, 0, 0, 0, 0)   | quantitykind:Mass                     |
| Mass per length               |              | Kg/m        | IfcMassPerLengthMeasure              | (-1, 1, 0, 0, 0, 0, 0)  | quantitykind:MassPerLength            |
| Modulus of elasticity         |              | N/m2        | IfcModulusOfElasticityMeasure        | (-1, 1, -2, 0, 0, 0, 0) | quantitykind:ModulusOfElasticity      |
| Moisture diffusivity          |              | m3/s        | IfcMoistureDiffusivityMeasure        | (3, 0, -1, 0, 0, 0, 0)  |                                       |
| Molecular weight              |              | Kg/mol      | IfcMolecularWeightMeasure            | (0, 1, 0, 0, 0, -1, 0)  | quantitykind:MolarMass                |
| Moment of inertia             |              | m4          | IfcMomentOfInertiaMeasure            | (4, 0, 0, 0, 0, 0, 0)   | quantitykind:MomentOfInertia          |
| PH                            |              | PH          | IfcPHMeasure                         | (0, 0, 0, 0, 0, 0, 0)   |                                       |
| Planar force                  |              | Pa          | IfcPlanarForceMeasure                | (-1, 1, -2, 0, 0, 0, 0) | quantitykind:ForcePerArea             |
| Angle                         | radian       | rad         | IfcPlaneAngleMeasure                 | (0, 0, 0, 0, 0, 0, 0)   | quantitykind:Angle                    |
| Plane angle                   | radian       | rad         | IfcPlaneAngleMeasure                 | (0, 0, 0, 0, 0, 0, 0)   | quantitykind:PlaneAngle               |
| Power                         | watt         | W           | IfcPowerMeasure                      | (2, 1, -3, 0, 0, 0, 0   | quantitykind:Power                    |
| Pressure                      | pascal       | Pa          | IfcPressureMeasure                   | (-1, 1, -2, 0, 0, 0, 0) | quantitykind:Pressure                 |
| Radio activity                | Becqurel     | Bq          | IfcRadioActivityMeasure              | (0, 0, -1, 0, 0, 0, 0)  | quantitykind:Activity                 |
| Ratio                         | Percent      | %           | IfcRatioMeasure                      | (0, 0, 0, 0, 0, 0, 0)   | quantitykind:DimensionlessRatio       |
| Rotational frequency          | hertz        | Hz          | IfcRotationalFrequencyMeasure        | (0, 0, -1, 0, 0, 0, 0)  |                                       |
| Section modulus               |              | m3          | IfcSectionModulusMeasure             | (3, 0, 0, 0, 0, 0, 0)   | quantitykind:SectionModulus           |
| Sound power                   | decibel      | db          | IfcSoundPowerMeasure                 | (0, 0, 0, 0, 0, 0, 0)   | quantitykind:SoundPowerLevel          |
| Sound pressure                | decibel      | db          | IfcSoundPressureMeasure              | (0, 0, 0, 0, 0, 0, 0)   | quantitykind:SoundPressure            |
| Specific heat capacity        |              | J/Kg K      | IfcSpecificHeatCapacityMeasure       | (2, 0, -2, 0, -1, 0, 0) | quantitykind:SpecificHeatCapacity     |
| Temperature rate of change    |              | K/s         | IfcTemperatureRateOfChangeMeasure    | (0, 0, -1, 0, 1, 0, 0)  | quantitykind:TemperaturePerTime       |
| Thermal conductivity          |              | W/m K       | IfcThermalConductivityMeasure        | (1, 1, -3, 0, -1, 0, 0) | quantitykind:ThermalConductivity      |
| Temperature                   | kelvin       | K           | IfcThermodynamicTemperatureMeasure   | (0, 0, 0, 0, 1, 0, 0)   | quantitykind:ThermodynamicTemperature |
| Time                          | second       | s           | IfcTimeMeasure                       | (0, 0, 1, 0, 0, 0, 0)   | quantitykind:Time                     |
| Torque                        |              | N m         | IfcTorqueMeasure                     | (2, 1, -2, 0, 0, 0, 0)  | quantitykind:Torque                   |
| Vapor permeability            |              | Kg / s m Pa | IfcVaporPermeabilityMeasure          | (0, 0, 1, 0, 0, 0, 0)   |                                       |
| Volume                        | cubic meter  | m3          | IfcVolumeMeasure                     | (3, 0, 0, 0, 0, 0, 0)   | quantitykind:Volume                   |
| Volumetric flow rate          |              | m3/s        | IfcVolumetricFlowRateMeasure         | (3, 0, -1, 0, 0, 0, 0)  | quantitykind:VolumeFlowRate           |

**Comment by berlotti** [comment]
Thank you!
Updated in wiki: https://github.com/buildingSMART/IDS/wiki/Physical-Quantities-and-Units
