### ISSUE TITLE
Question: matching case on IFC type name

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#49]
Hello all,

I was wondering where we stand when it comes to case sensitivity matching strings.

An 'xs:pattern' on a property name should probably be case sensitive, but what if somebody sets the a 
patter constraint for `IFCWALL` vs. `IFCwall`? I would argue that against schema parts (i.e. types, predefined types, class attributes...)
a user might reasonably expect some freedom.

Should we vote on this?

Also, I think that we should start documenting these decisions in the repository.

Best,
Claudio

**Comment by NickNisbet** [comment]
Not only should these point be documented in the repository but also users are going to need realistic examples and prompts in the user interfaces.

Are these valid for a selection and for an Exception?

  *   Ifc(Window|Door)Type
  *   Ifc^(OpeningElement).*

**Comment by berlotti** [comment]
Decision
 
Follow the XSD Pattern standard: everything case sensitive.
For entities of IFC we use ALL UPPERCASE.

note for IDS Validator: check if entities in IDS are all upper case.
