### ISSUE TITLE
example questions

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#5]
Hello,

is the use of the `xs:` namespace intentional in the example below? 

https://github.com/buildingSMART/IDS/blob/d86f4a55d00e7bf0431d471fb4c8bbcc0f0225ab/Development/First%20production%20release/Examples.md#L84-L88

**Comment by CBenghi** [comment]
Hi Again,

I would also suggest that the naming `property` should not be repeated for element at lines 80 and 82

https://github.com/buildingSMART/IDS/blob/d86f4a55d00e7bf0431d471fb4c8bbcc0f0225ab/Development/First%20production%20release/Examples.md#L80-L82

**Comment by aothms** [comment]
> intentional

I think so, but I'm not sure if it has to be.

For reference I have the following complete IDS file with XSD namespace that I have used for testing. It reports some failures and successes for Duplex_a.

```
<ids xmlns="http://standards.buildingsmart.org/IDS/todo" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <specification name="vaste wand, othername">
        <applicability>
            <entity>
                <name>IfcSpace</name>
            </entity>
        </applicability>
        <requirements>
            <property>
                <propertyset>PSet_Revit_Identity Data</propertyset>
                <property href="http://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/prop/FireRating">Name</property>
                <value>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Living Room" />
                        <xs:enumeration value="Kitchen" />
                    </xs:restriction>
                </value>
            </property>
        </requirements>
    </specification>
</ids>
```

**Comment by CBenghi** [comment]
Thanks @aothms,
With the added namespace it makes sense.
I guess the plan is to include the full set of restrictions from the xml standard, then.

**Comment by aothms** [comment]
Yes I think at patterns and min/max bounds are somewhere in these milestones, but I'm not sure how much of XSD that covers.
