### ISSUE TITLE
Interpretation of attributeType with empty value

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#54]
Hi folks,

the attribute type does not mandate a value, it is optional.

If we leave it empty:

1. can it be null? I.e. we have a positive match for any element belonging to a class that **could have** the attribute, or 
2. does it have to be not null?

The IFC schema in this case is different from the property case. For properties we can check that an instance of IfcPropertySingleValue (instance containing the value) exists or not, whereas here the containing instance always exist (it's the entity we are checking itself).

For conceptual symmetry (and implementation reuse) I would prefer option 1, but then I'd probably have a conversation to see if 
it makes sense to mark the value required.
An empty value, would just be a different way to identify a set of entities by type.

Claudio

**Comment by CBenghi** [comment]
Hello,
I'm uploading a visual to help the conversation next time around as suggested by Robin.

![image](https://user-images.githubusercontent.com/5476273/157411312-af240377-255b-428f-96e0-be18ded64387.png)

**Comment by dro007** [comment]
Meeting on 15 March 2022:
It was suggested that a value constraint will be required on all attributes, subject to clarification on wording. Initial suggestion by Claudio.
Check semantic difference between null value and absent property with IFC core team.
Check how bsDD team handle null values versus empty values.

**Comment by Moult** [comment]
I propose if Name is specified, it implies the value should be not null, not whether the attribute can exist. Whether or not an attribute can exist is semantically more relevant to the Entity facet, not the Attribute facet I believe.

Also, most of the industry's users and tools don't or can't see the difference between null and empty string, so maybe both should be treated as null? 0, however, is a value.

**Comment by Moult** [comment]
The various permutations of nullness have been documented in the test cases, so closing.
