### ISSUE TITLE
cardinality question

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#57]
In the latest schema minOccurs and maxOccurs are defined as integers and we're not reusing the `xs` namespace objects. 
in the `xs` namespace they are not strictly integer, though, as `maxOccurs` can be `unbounded`.

In any case we have to define the default value when the attributes are not defined in the files. In the `xs` namespace  their default is `1`.

If this is the case, we have also to change sample files to set maxOccurs to 'unbounded' where minOccurs is "1".

Finally, they type should be a nonNegativeInteger instead of Integer.

  maxOccurs = (nonNegativeInteger | unbounded)  : 1
  minOccurs = nonNegativeInteger : 1

**Comment by berlotti** [comment]
Good catch!
Refered to the correct source in 0.6.1: [e3c0f0b](https://github.com/buildingSMART/IDS/commit/e3c0f0baa4ef30409b944642b2bef2a0d46deefe)
