### ISSUE TITLE
Property elements naming

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#6]
Hello

There are two elements in the example schema with the same name but different structure.
I would suggest that the naming `property` should not be repeated for elements at lines 80 and 82

https://github.com/buildingSMART/IDS/blob/d86f4a55d00e7bf0431d471fb4c8bbcc0f0225ab/Development/First%20production%20release/Examples.md#L80-L82

**Comment by aothms** [comment]
I agree, in line with the IFC schema, that should probably be `name` then?

**Comment by CBenghi** [comment]
I would agree on `name` if it was an attribute.
Since it's been structured as an element It doesn't seem quite as elegant.
Maybe we can involve more views in the call next week.

In general I would prefer using attributes in this scenario:

``` xml
<property propertyset="AedesUVIP" name="Firerating" href="http://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/prop/FireRating">
	<xs:restriction base="xs:string">
		<xs:enumeration value="30" />
		<xs:enumeration value="60" />
		<xs:enumeration value="90" />
	</xs:restriction>
</property>
```

To be clear I don't mind much... it's just one of those small things that nag my weak mind ;-)

**Comment by aothms** [comment]
I agree, as you said (I think it was you) during previous call, consistency is important. It helps implementation and reduces potential errors in authoring. And we have value as an attribute from XSD

The benefit of child nodes is that you can later expand them into different kinds of nodes, xs:restriction on name, who knows.

Let's discuss next week :)

**Comment by berlotti** [comment]
We probably want to add restrictions to propertySetNames, name of property and other things later on. I'm actually quite sure that will happen. 
Extendibility in the future is also easier to keep it in separte nodes.

**Comment by CBenghi** [comment]
Ok, but what about the duplicate `property` name?

**Comment by berlotti** [comment]
changed the example. I'm also not happy with 'name' but lets go for it for now.
