### ISSUE TITLE
Default values of minOccurs and maxOccurs

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/IDS#60]
`xs:occurs` from the XML schema definition is also used in the IDS schema, e.g. for definition of `specificationType, propertyType, materialType` etc. I wonder about default values. According to [XMLSchema.xsd](https://www.w3.org/2001/XMLSchema.xsd) it looks to me that it is both 1. Can you confirm?

<xs:attributeGroup name="occurs">
<xs:annotation>
<xs:documentation> for all particles</xs:documentation>
</xs:annotation>
<xs:attribute name="minOccurs" type="xs:nonNegativeInteger" use="optional" default="1"/>
<xs:attribute name="maxOccurs" type="xs:allNNI" use="optional" default="1"/>
</xs:attributeGroup>

**Comment by MatthiasWeise** [comment]
Thank you for the link and confirmation! 
So, unless we require exactly 1 (min/maxOccurs = 1) we need to state that in IDS. 
I think we can close this issue/question then.

**Comment by CBenghi** [comment]
Hi @MatthiasWeise,
perhaps reopen it until we add the documentation 
(@berlotti tagged this to document).
Hopefully the Documentation hackathon will happen soon.

**Comment by MatthiasWeise** [comment]
I am reopening this issue as I do not see that this topic is reflected in the documentation yet. Also, if default min/maxOccurs = 1, then I guess many examples need to be updated (see comments from CBenghi in the other issue).

**Comment by Moult** [comment]
I didn't add it to the docs because I thought it's just known that the default XML values are 1.

Note the allowed values are documented here: https://github.com/buildingSMART/IDS/blob/master/Documentation/developer-guide.md#optionality

All testcases should have the correct optionality.

**Comment by MatthiasWeise** [comment]
@Moult Thank you for the link to the documentation (sorry I did not take notice of this page so far). 

Regarding examples: I was referring to the examples published with IDS 0.9 specification (not your testcases, although they seem to have some upper case issue for entity applicability - you most likely know already).

**Comment by Moult** [comment]
@MatthiasWeise I was told that IFC entities are meant to be specified as uppercase. There is a testcase for that. Feel free to debate it though, I'm just the testcase writer :)

Personally, I'm not a fan of the uppercase, but hey ;)

**Comment by MatthiasWeise** [comment]
The uppercase decision for entities was most likely due to the SPF convention (just guessing). 
I am personally used to camel case for IfcEntities, but this decision is no dealbreaker and no need to discuss any further ;-) 

May check [this](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/attribute/pass-a_required_facet_checks_all_parameters_as_normal.ids) and other examples (IfcWall -> IFCWALL in line 10).
