### ISSUE TITLE
Constraints on property with measure

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#61]
For discussion and documentation:

When specifying a property with a measure (other than string and number) values will have to be transformed from the unit defined in the model to the relevant SI unit for testing.

So I propose that any relevant `restriction` adheres to the following implementation agreements:

- [ ] we should expect base type to be double.
- [ ] pattern and structure restrictions should be considered invalid (as they do not make sense on the converted value)

**Comment by berlotti** [comment]
now using IFC defined types, still with fixed values.
We might need to make a list of what xs base types map to what ifc defined types (with fixed units).

Patterns could still be valid.

**Comment by CBenghi** [comment]
I've added the capability to constrain valid `xs:facets` depending on the base type of restrictions.
For the time being this is constrained to the types defined in the XML documentation, but we might want to implement stricter implementation agreements.

**Comment by atomczak** [comment]
The list of mappings is already documented in: https://github.com/buildingSMART/IDS/blob/development/Documentation/ImplementersDocumentation/DataTypes.md and https://github.com/buildingSMART/IDS/blob/development/Documentation/UserManual/units.md. The restrictions are possible.
