### ISSUE TITLE
Numeric formats and deterministic pattern matches

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#63]
Given that number types in the xsd schema have multiple valid literal representations for numeric values

> For example, -1E4, 1267.43233E12, 12.78e-2, 12 , -0, 0 and INF are all legal literals for float.

is it worth defining a string conversion logic that allows us to apply unequivocally pass/fail tests related to patterns?

The concern:
- someone might look for a pattern match like `\d\d\.\d\d`
- `12.34` would match, however `1.234e+1` which represents the same number, would fail just because of a different valid representation.

How to we prevent this?

**Comment by CBenghi** [comment]
Hi @aothms,

The automatic mapping to the native value (and back to string) is exactly my concern here.

If I read an ifc file with `IfcAreaMeasure(12.34)` or `IfcAreaMeasure(1.234e+1)` my toolkit receives the same native double value in c#.

To check that double against a pattern like `\d\d\.\d\d` I would have to convert it to a string format, and there lies the risk of inconsistency if different conversion methods prefer scientific notation versus decimal presentation in different circumstances.

It might be an unusual scenario, but I thought it was worth discussing.

**Comment by aothms** [comment]
Ok, then I indeed think I misunderstood. I thought you were worried about the pattern of the numeric value specified in IDS, but your concern is the usage of xs:pattern in restrictions on numeric fields?

I don't think patterns for numbers is a very meaningful use case. Would one have control over it in an authoring tool? I would simply vote for disallow.

This does remind me of the behaviour of string matching an character encoding https://github.com/buildingSMART/IDS/issues/64

**Comment by CBenghi** [comment]
Indeed,
disallowing is an option, the other would be a predetermined string conversion routine.
I would probably vote for disallowing :-)
Claudio
