### ISSUE TITLE
Redundant measure enumeration (Ratio)

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#66]
In the enumeration values for property measure
https://github.com/buildingSMART/IDS/blob/d4c12f6345a95889494ef4517f1e2135f98437ee/Development/0.6/ids_06.xsd#L80-L86

we include the option for `Ratio`
https://github.com/buildingSMART/IDS/blob/d4c12f6345a95889494ef4517f1e2135f98437ee/Development/0.6/ids_06.xsd#L131

but I think it should be removed because `ratio` - contrary to all other values - does not have a match in one of the standard UnitTypes in `IfcDerivedUnitEnum` and `IfcUnitEnum`.

The use case for ratio can be expressed using the `Number` option instead, because no unit conversion is required, anyway, being a pure number.

**Comment by berlotti** [comment]
now using IFC defined types (0.9)
