### ISSUE TITLE
Question: removed measure enumeration

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#68]
Hello,

Evaluating changes between 0.6 and 0.9 I'm reading the following code:
https://github.com/buildingSMART/IDS/blob/8b25b29efae09c5e1c76f4183471e21615cfe420/Development/0.9/ids_09.xsd#L86-L90

In my understanding the enumeration was required to be able to specify the nature of the expected measure and then perform the right conversion to the relevant SI Unit, should any value constraint be specified.

By making the field into a `ids:value` we could require that some property could accept, for instance, either a length or an area.
Would this not be a bit confusing, and perhaps the sign of a poorly defined exchange plan?

I suppose that we could use directly the type defined in the IFC to perform the right conversion to the standard SI unit, but then the value constraint would probably never make sense for any facet accepting multiple types of measure.

My view is that the enumeration available in 0.6 made and IDS xml easier to fill in.

Just my two cents, I appreciate that functionally this could still work.

Best,
Claudio

**Comment by aothms** [comment]
In my understanding:

> the enumeration was required to be able to ... perform the right conversion to the relevant SI Unit, should any value constraint be specified.

The same table is still in effect, to do the unit lookup when a numeric measure is selected

It however much more natural now to select IfcBoolean, IfcText, etc. 

> either a length or an area

True. Indeed not so useful for Length|Area, but for Text|Label or Integer|Real (or how about PositiveInteger|Integer, we never talked about the "inheritance" of simple types) I do see clear compelling reasons to support this.

> but then the value constraint would probably never make sense for any facet accepting multiple types of measure

This is true. There are couple of patterns possible that don't make much sense. But in general value constraints for numeric measures isn't the biggest priority given the use cases. So I think trading in some nonsensical options here for easily allowing Text|Label|Identifier (which a UI could present as any kind of text input) I think is the right kind of trade-off.

The enumeration was also inconsistent with how we referred to entities. (The same applies there, you can make nonsensical patterns).

**Comment by CBenghi** [comment]
Hi @aothms, 
I agree completely, I had missed the fact that we can now reference directly the IfcType.
This is good.
