### ISSUE TITLE
Testcase "[FAIL] Durations are treated as strings 1/2"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#71]
[[FAIL] Durations are treated as strings 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-attribute.md#fail-durations-are-treated-as-strings-12)
Shouldn't that be PASS?
(Like this [[PASS] Durations are treated as strings 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#pass-durations-are-treated-as-strings-12))

PS: I will open some issues to the testcases. A issue for every question. Sorry for flooding the issue tab, but there is more overview when each issue can be closed individually than when I do a single big issue.

**Comment by Moult** [comment]
This is great! I haven't yet proof read all of them so I'll go through tomorrow :)

Agreed that one looks ... Just wrong entirely :) looks like I copy pasted the date tests and didn't change it.
