### ISSUE TITLE
Testcase "[FAIL] Attributes are not inherited by the occurrence"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#72]
[[FAIL] Attributes are not inherited by the occurrence](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-attribute.md#fail-attributes-are-not-inherited-by-the-occurrence)
Is this example/testcase clear? Wouldn't it be clearer with something like:
`#1=IFCWALL('0y2FiE76f9BQiJ5jrpELFo',$,'Bar',$,$,$,$,$,$);`
`#2=IFCWALLTYPE('35Sc4Leab3$vdTXdBsrq3i',$,$,$,$,$,$,$,$,.ELEMENTEDWALL.);  /* Testcase */`
`#3=IFCRELDEFINESBYTYPE('2w2JAq$NT8v9osGH38S_9p',$,$,$,(#1),#2);`

Maybe I don't understand the testcase/example? What does the test case show?

**Comment by Moult** [comment]
Agree
