### ISSUE TITLE
Testcase "[FAIL] Name restrictions may be used 3/4"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#73]
[[FAIL] Name restrictions may be used 3/4](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-attribute.md#fail-name-restrictions-may-be-used-34)
For attributename restrictions with an enum each(!) enum value must match - that's how I read the testcase. Right?
So the enum values have a AND logic to each other.

But for value checks the enum values have OR logic: [[PASS] Value restrictions may be used 1/3](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-attribute.md#pass-value-restrictions-may-be-used-13)

Is that consistent? 

I would read testcase
`<attribute minOccurs="1" maxOccurs="1">`
`  <name>`
`    <xs:restriction base="xs:string">`
`      <xs:enumeration value="Name"/>`
`      <xs:enumeration value="Description"/>`
`    </xs:restriction>`
`  </name>`
`</attribute>`
as "the entity must have the attribute 'Name' OR the attribute 'Description'".
If both attributes are required, I would create two seperate attribute requirements. Something like
`<attribute minOccurs="1" maxOccurs="1">`
`  <name>`
`    <simplevalue>Name</simplevalue>>`
`  </name>`
`</attribute>`
&
`<attribute minOccurs="1" maxOccurs="1">`
`  <name>`
`    <simplevalue>Description</simplevalue>>`
`  </name>`
`</attribute>`

Why should enum values for attributename have AND logic?

**Comment by Moult** [comment]
Agreed it is not consistent. I agree that it should be changed to any/or.
