### ISSUE TITLE
Testcase "[PASS] Occurrences override the type classification per system 3/3"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#74]
[[PASS] Occurrences override the type classification per system 3/3](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-classification.md#pass-occurrences-override-the-type-classification-per-system-33)

Isn't that FAIL? IfcWall (record no 18) has the classification value '11' (record no 9), so the classification value 'X' (record no 23) of IfcWallType (record no 19) is ignored for IfcWall. (?)

**Comment by Moult** [comment]
No, because X is part of Foobaz and 11 is part of Foobar. Overrides are per system.

**Comment by hesrah** [comment]
So IfcWall has two classification systems: 'Foobar' and 'Foobaz' and both are valid at the same time. A little confusing ... ;-)
