### ISSUE TITLE
Testcase "[FAIL] Material with no data will fail a value check"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#75]
[[FAIL] Material with no data will fail a value check](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-material.md#fail-material-with-no-data-will-fail-a-value-check)
Why doesn't "Material" have no data?
`#2=IFCMATERIAL('Unnamed',$,$);`
Is 'Unnamed' no data? (One could argue about the meaning ...)

**Comment by Moult** [comment]
Same as material list bug
