### ISSUE TITLE
Testcase "[FAIL] A material list with no data will fail a value check"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#76]
[[FAIL] A material list with no data will fail a value check](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-material.md#fail-a-material-list-with-no-data-will-fail-a-value-check)
Material list **HAS** data with record no 4?
`#1=IFCWALL('05rScmOVzMoQXOfbYdtLYj',$,$,$,$,$,$,$,$); /* Testcase */`
`#2=IFCMATERIALLIST((#4));`
`#3=IFCRELASSOCIATESMATERIAL('05rScmOVzMoQXOfbYdtLYj',$,$,$,(#1),#2);`
`#4=IFCMATERIAL('Concrete',$,'CONCRETE');`

**Comment by Moult** [comment]
Yes, invalid test and should be deleted, it was originally written to handle invalid IFC data, but since invalid data (e.g missing mandatory material) is out of scope, it shouldvew been removed but I forgot.
