### ISSUE TITLE
Testcase "[FAIL] Properties with a null value fail"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#77]
[[FAIL] Properties with a null value fail](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#fail-properties-with-a-null-value-fail)
The Property has value "IFCLABEL('AnotherValue')"not null value. (?)
Should it instead of
`#10=IFCPROPERTYSINGLEVALUE('AnotherProperty',$,IFCLABEL('AnotherValue'),$);`
stand
`#10=IFCPROPERTYSINGLEVALUE('AnotherProperty',$,$,$);`?
Otherwise it would be PASS (but doesn't really demonstrate the testcase)?

**Comment by Moult** [comment]
Yep, code error will fix.
