### ISSUE TITLE
Testcase "[FAIL] Measures are used to specify an IFC data type 1/2"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#79]
[[FAIL] Measures are used to specify an IFC data type 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#fail-measures-are-used-to-specify-an-ifc-data-type-12)
Why is this FAIL?
Seem to me the same as [[PASS] Measures are used to specify an IFC data type 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#pass-measures-are-used-to-specify-an-ifc-data-type-22), once with IfcMassMeasure once with IfcTimeMeasure? What makes the difference?

**Comment by Moult** [comment]
It fails because the ids requests a time measure but the Ifc contains a mass measure.

**Comment by hesrah** [comment]
Oh, yes! I didn't properly consider the measure attribute of the property tag. Close the issue please.
