### ISSUE TITLE
Testcase "[PASS] Properties can be inherited from the type 1-2/2" and "[PASS] Properties can be overriden by an occurrence 1-2/2"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#80]
[[PASS] Properties can be inherited from the type 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#pass-properties-can-be-inherited-from-the-type-12)
[[PASS] Properties can be inherited from the type 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#pass-properties-can-be-inherited-from-the-type-22)
[[PASS] Properties can be overriden by an occurrence 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#pass-properties-can-be-overriden-by-an-occurrence-12)
[[FAIL] Properties can be overriden by an occurrence 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#fail-properties-can-be-overriden-by-an-occurrence-22)
It seems that in all cases the relation record between PropertySet and IfcWallType is missing?
Add line `#93=IFCRELDEFINESBYPROPERTIES('.......',$,$,$,(#89),#91);`

**Comment by Moult** [comment]
Element types have a direct HasProperties attribute and don't need that rel.

**Comment by hesrah** [comment]
I see!
