### ISSUE TITLE
Testcase "[FAIL] Attributes are not inherited by the occurrence" II

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#84]
Sorry, I have to come back on this testcase again (#72): [[FAIL] Attributes are not inherited by the occurrence](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-attribute.md#fail-attributes-are-not-inherited-by-the-occurrence)

I think now it should be PASS? And the testcase doesn't test/demonstrate what the title means.
Or I didn't understand ...

**Comment by Moult** [comment]
The ids wants the wall's description to be foobar.

The wall does not have a description of foobar. The wall type does, but attributes are not inherited (unlike props, materials, classifications) so the wall type has no impact, so the test should fail.

**Comment by Moult** [comment]
Yeah that's how IFC has always worked.

Attributes are identifying metadata of an object, and an occurrence is a distinct and different object to its typology, so naturally attributes don't inherit. A wall and its wall type are two different objects with different names.

Props, classifications, materials are not unique identifiers but instead characteristics, and therefore make sense to have type inheritance and occurrence override rules.

**Comment by hesrah** [comment]
Ok, makes sense :-)
