### ISSUE TITLE
Purpose of optional attribute specification

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS#85]
Hello,

may I ask what is the purpose of the following specification?

https://github.com/buildingSMART/IDS/blob/31885452a6ec064ab6f853746ea4f73817cdb713/Documentation/testcases/attribute/pass-an_optional_facet_always_passes_regardless_of_outcome_2_2.ids#L15-L19

I think to recall that optional requirement facets would mean "if they exist they must match the value constraint"... or something along that line, but I cant' figure out what to do if any value constraint is missing.

I can't figure out a use case, thanks.

**Comment by Moult** [comment]
https://github.com/buildingSMART/IDS/blob/master/Documentation/specifications.md#required-and-optional-specifications-and-facets

Usage can be on either specs or on facets. You've described the spec behavior.

Yes, optional on a facet is pretty useless.

**Comment by hesrah** [comment]
I propose adding a value element to this testcase.
Then it means "if the attribute 'Rabbit' exist, it has to satisfy the requirement". Or how would you check this case?

**Comment by Moult** [comment]
@hesrah I think you're misreading the testcase, the attribute Rabbit is in the requirements section, not the applicability section. Can you please reread the doc link I posted above and see if that clarifies things?

Here's an alternate proposal: facet usage must only be required or prohibited, do not allow optional. Spec usage can be all three: required, optional, prohibited.

**Comment by hesrah** [comment]
I see, yes, the value element doesn't help. 
So I propose that 'optional' (minOccurs="0") for a facet could be used as a recommendation. A checker tool could then put out a warning instead of an error. (?) Anything else doesn't make sense and "is pretty useless" indeed ...

**Comment by Moult** [comment]
@hesrah yes, right now, it is used merely as a recommendation. Right now the test cases only check two states, pass or fail, I guess warning is a good option.

**Comment by CBenghi** [comment]
I personally would not introduce warnings.
I see reducing ambiguity as a central merit of the project

Along the same line I would constrain the use of min/max to their required/prohibited configurations only, when it comes to the   individual facet.

(Optional would still be valid for specifications, obviously)

This was a long conversation in a few of the calls before @Moult was brought on board, perhaps we can resume it now with greater insight.

**Comment by aothms** [comment]
> So I propose that 'optional' (minOccurs="0") for a facet could be used as a recommendation. A checker tool could then put out a warning instead of an error. (?)

> I personally would not introduce warnings.
> I see reducing ambiguity as a central merit of the project

In itself, a third result state isn't going to introduce ambiguity, but it's indeed late in the game of introducing this. I see three options:

- Disable optional on facet
- Require optional facet to emit warning
- Require optional facet to **not** log error, the rest is non-normative

I personally would vote for the last, it allows us to see how this will be used in practice and gives acceptable freedom to implementers. I think optional clauses are quite common in graph query languages, e.g sparql. Having to deal with inconsistent data and given the fact we don't have OR, I'd vote for keeping optional facets in the spec.

> Along the same line I would constrain the use of min/max to their required/prohibited configurations only, when it comes to the individual facet.

I think I'd support this, at least for v1. There's isn't really a use case for requiring a property needing to be present twice. And it's definitely an area where we can imagine implementation differences: How to count? Case sensitivity? Does the implementation even support counting in their data model, or does it use sets and maps? Etc.

**Comment by hesrah** [comment]
> - Require optional facet to **not** log error, the rest is non-normative

I wanted to suggest that too.
For example, a checker tool may have an option "Warning on Recommendation". But not as a normative part of IDS.

**Comment by hesrah** [comment]
> There's isn't really a use case for requiring a property needing to be present twice.

For example, when working with a pattern for Property names, you may have a PropterySet with a list of ten Propertys with similar names (that all fit the pattern) and you want three of the Propertys to be required, but they don't have to be the same three each time.
It may not be ordinary, but it is imaginable.

**Comment by CBenghi** [comment]
In line with @aothms suggestion I would introduce another important concept in IDS: validity of requirements and facets.

To ensure consistency across implementation we should have ways to evaluate what requirements and facets are 
valid or invalid.

Only valid requirements should be used to produce reports on models.

This would remove any controversy that might be arising from a model failing an invalid requirement, and clearly place the responsibility on the author of the requirement.

I would gladly contribute to a test harness for valid/invalid facets.

**Comment by Moult** [comment]
@CBenghi maybe getting off-topic for this issue, but what validity do you mean?

**Comment by CBenghi** [comment]
Hi @Moult, I agree is edging towards a different topic, but it might offer a solution for this issue too.

Invalid elements might be:

- facets have required properties (e.g. Entity requires Name), if such properties are missing, then a facet is invalid 
- a pattern constraint with wrong pattern syntax would invalidate the parent facet
- a maxOccur smaller than a minOccur

Maybe some more refined rules could be conceived such as:

- using an inverse attribute name in the attribute facet (I read they are considered invalid)
- using a non existing class name in the entity facet

And even more complex such as:

- using a regex pattern in attribute name that does not match any existing ifc attribute


If a facet is invalid would invalidate the parent requirement, and these would not be reported when verifying a model.

**Comment by Moult** [comment]
For a bit of closure on this, is the addition sufficient?
