### ISSUE TITLE
What ist the prefered design for a specificaten with "prohibited"? 

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/IDS#90]
Try to move a discussion in Slack to Github 
see https://app.slack.com/client/T02P2T7AD9S/C02NL0SL1EK/thread/C02NL0SL1EK-1662726886.750049

![grafik](https://user-images.githubusercontent.com/6228972/191442446-fea23f95-aab0-4074-a005-4302dfa182b6.png)

**Comment by MatthiasWeise** [comment]
![grafik](https://user-images.githubusercontent.com/6228972/191443050-4e4fd5f8-7709-4f59-8c76-419be83c7a78.png)

**Comment by MatthiasWeise** [comment]
![grafik](https://user-images.githubusercontent.com/6228972/191443240-ee75c68e-ce03-41b3-9818-4b30c3631da6.png)

**Comment by MatthiasWeise** [comment]
![grafik](https://user-images.githubusercontent.com/6228972/191443420-7d7cb549-46fa-4641-98d3-f56814de7433.png)

**Comment by MatthiasWeise** [comment]
![grafik](https://user-images.githubusercontent.com/6228972/191443635-52336f1b-734a-4d25-a7ce-77d2fbae4030.png)

**Comment by MatthiasWeise** [comment]
![grafik](https://user-images.githubusercontent.com/6228972/191443786-a954aaab-d149-4b24-8e9c-242ec305ed70.png)

**Comment by Moult** [comment]
I read through and I'm not entirely sure what the question or proposal is.

If the proposal is to add the occurs attribute to applicability, I disagree, we already have occurs on specification and that seems sufficient.

**Comment by MatthiasWeise** [comment]
@Moult How to best handle existence of objects via occurs.

**Comment by Moult** [comment]
The relationship depends on the occurs on the spec. Isn't the meaning already made unambiguous and clear in the first table here? https://github.com/buildingSMART/IDS/blob/master/Documentation/specifications.md#required-and-optional-specifications-and-facets or have I missed a logical permutation? I'm very poor at reading logical notation can you help translate that to text?

**Comment by MatthiasWeise** [comment]
@Moult Please see possible options posted in the first comment. 
Option a) is not possible due to XSD restriction, **but maybe there are cases to allow this** and maybe allow occurs for Applicability.
Option c) everybody agrees that this correct
Option b) **different opionions if that is equal to c or not** leading to a fundamental question about model checking.

**Comment by Moult** [comment]
The testcases should already cover b and c and should remove any ambiguity

See: https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-ids.md#pass-prohibited-specifications-fail-if-at-least-one-entity-passes-all-requirements-13

Option b) is interpreted in the testcases as "if there is a wall with a fire rating, then fail". So:

 - PASS: No walls
 - PASS: wall without fire rating
 - PASS: slab with fire rating
 - FAIL: wall with fire rating

Option c) is interpreted in the testcases as "if no walls, pass, but if there is a wall, they must not have a fire rating". So:

 - PASS: No walls
 - PASS: wall without fire rating
 - PASS: slab with fire rating
 - FAIL: wall with fire rating

So b and c are equal according to the current documentation and testcases. Happy for someone to propose a change, and I'll happily document and adjust the test cases, but what I've described _should_ already be unambiguous in the test cases.

**Comment by MatthiasWeise** [comment]
Thanks, that perfectly fits to my understanding of checking rules. No need to change documentation.

What about check for existence of IfcSpace objects (without any data requirement or a data requirement that cannot be expressed via existing IDS facets)?

**Comment by Moult** [comment]
Yeah that situation is something I came across too and for that reason I once proposed verbally that requirements might possibly be left out.

However for now I use a hack, either repeating the entity in the requirements section or checking an attribute globalid.

It's not pleasant.

**Comment by MatthiasWeise** [comment]
Good point! I havn't thought about using an entity facet in the requirements but yes that would do the trick (kind of tautology expression). In fact, I would prefer such solution over asking for a mandatory attribute like GlobalId. Anyhow, making Requirements optional would be even better. 

Regarding entity check: Do we have a way to ask for an object (occurrence) being typed by a specific type object? This is relevant for IFC2x3 where occurrence definitions are not fully aligned with type definitions as in IFC4.

**Comment by Moult** [comment]
> Do we have a way to ask for an object (occurrence) being typed by a specific type object?

Currently no. Potentially an extension of the "PartOf" facet might be a good proposal. Though the partOf facet right now only has "entity" and "relationship" which I find rather limited, I think adding "Name" would make it very useful.

**Comment by MatthiasWeise** [comment]
I am not happy about mixing semantic meaning "PartOf" with "TypedBy" definition. 

I also agree that checking relationship is rather limited. However, current solution follows KISS principle for easy implementation (ok for now if it does the job). Anyhow, I expect that we will add attributes here and there to cover new features, all leading to new versions of IDS.

**Comment by Moult** [comment]
In that case I'd propose to leave the ability to ask for an object to be typed by a particular type as a "not available in IDS v1". Best to let it grow organically through user feedback instead of trying to preempt everything.

**Comment by hesrah** [comment]
> What about check for existence of IfcSpace objects (without any data requirement or a data requirement that cannot be expressed via existing IDS facets)?

What about an empty requirement element? Like:
```
<ids:ids ...">
    <ids:info> ... </ids:info>
    <ids:specifications>
        <ids:specification name="Spaces" minOccurs="1" maxOccurs="unbounded" ifcVersion="IFC4">
            <ids:applicability>
                <ids:entity>
                    <ids:name>
                        <ids:simplevalue>IfcSpace</ids:simplevalue>
                    </ids:name>
                </ids:entity>
            </ids:applicability>
            <ids:requirements>			
            </ids:requirements>
        </ids:specification>
    </ids:specifications>
</ids:ids>
```

NB: It's not valid with the current XSD. Needs `minOccurs="0"` added in line 115.

**Comment by Moult** [comment]
See https://github.com/buildingSMART/IDS/issues/90#issuecomment-1253790731

**Comment by hesrah** [comment]
I meant an empty requirement element, not leaving out the requirement element. In the same manner as a material facet: [empty material facet](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-material.md#pass-a-required-facet-checks-all-parameters-as-normal).

I know, at the end it doesn't change anything semantically. It's semantically the same as the comment above. But I prefer an empty element instead of an omission. The design is then more consistent (with e.g. the material facet) and clear.
I'm not very happy about the idea with the tautological entity element in the requirement. It's more confusing.
Granted, it's more a matter of design style.

**Comment by berlotti** [comment]
changed minoccurs to 0 on requirements in  commit [94d2501](https://github.com/buildingSMART/IDS/commit/94d25016eebefb2bd60fe8dd718e8b11164bd852)
