### ISSUE TITLE
"partofentity" instead of "entity" in partof element

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#91]
In the xsd file, the partOfType and the applicabilityType both have the subelement "entity" which don't mean the same.
I prefer that these subelements have different names. E.g. "partofentity" (or similar) for the subelement of partOfType.

**Comment by berlotti** [comment]
the 'entity' facet there is actually the same as the other one (not a different one with the same name, but really the same one being reused).
Advantage of reusing it is that validator tools can check the same requirements.

**Comment by hesrah** [comment]
Ok, but if I understand your answer correctly, shouldn't line 61 be
   `<xs:element name="entity" type="ids:`**entityType**`" minOccurs="0"/>`
instead of 
   `<xs:element name="entity" type="ids:idsValue" minOccurs="0"/>`?

**Comment by berlotti** [comment]
Yes, you are right. 
It is indeed different but with the same name. Thank you for noticing!

Making it the same would include the 'predefinedType' to the options.
Do we want that?

So as I see it now there are two options:
- rename current element to 'partOfEntity'
- change to actual 'ids:entity' adding the option of predefinedType to 'partOf'

**Comment by aothms** [comment]
I prefer:

> change to actual 'ids:entity' adding the option of predefinedType to 'partOf'

I don't see a reason for them to be different

**Comment by hesrah** [comment]
I think 'ids:entityType' in XSD is good. PredefinedType in partOf does not disturb.

**Comment by CBenghi** [comment]
I can live with both scenarios, for full disclosure I've got an extended facet implementation that allows to reference a facet group, rather than just an entity.

That would allow us to define requirements for elements partaking a relationship with something more complex (e.g. something that matches both an entity facet and a classification facet).

I expect this would be a natural extension of the schema in the future.

**Comment by berlotti** [comment]
fixed in [be3ca8e](https://github.com/buildingSMART/IDS/commit/be3ca8efbba1d9bf64d012924b62b5e1d9d3fb12)
