### ISSUE TITLE
material facet has maxOccurs="1"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#92]
A question about the material facet: Why I can only have one material facet in a requirement? Is this a limitation from IFC?

**Comment by berlotti** [comment]
There are many many ways to do materials in IFC. 
In the use-cases we see, people only require one material to be placed in 'IfcMaterial'.
So that is what we agreed to do with the 'material' facet for now as well.

Since the material structure in IFC will change in IFC 5 this can be reevaluated after IFC5.

**Comment by hesrah** [comment]
Ok, thx.

We have a requirement for a wall with an interior material requirement and an exterior material requirement. That would require two separate material facets (or minOccurs="2" for the one material facet, which IDS does not want ...).

**Comment by berlotti** [comment]
Isn't that a requirement for an IfcCovering then?

**Comment by Moult** [comment]
It depends on the stage of the project. At earlier project phases projects typically used layered materials which encapsulate the covering layer. At later project phases it is more likely to be modeled as a separate covering. I've got the same usecase where it depends on the project phase.

**Comment by hesrah** [comment]
> Isn't that a requirement for an IfcCovering then?

Maybe(?). Isn't an IfcCovering the "surface"? How thick "should" an IfcCovering be?

**Comment by Moult** [comment]
I don't think IFC5 is going to change the fact that an object can have multiple materials, and the usecase described here, of layered materials, is so fundamental to especially the architectural discipline that I can't imagine it being removed.

**Comment by TLiebich** [comment]
in IFC (IFC2x3, 4 and 4.3) there is a single association to a material definition (in IFC4/4.3 enforced by a where rule at building/built element) - a material definition can either be a constituent, layer or profile SET (1 to many IfcMaterial) or (and discouraged as only a fallback to earlier implementation practise) by a single IfcMaterial.

So the default way to associate material to elements is by a set of materials (constituents, layers, profiles). Not sure how IDS reflects this.

**Comment by hesrah** [comment]
Thanks for the clarification.
So I guess we'll have to extend the material facet in an upcoming IDS version so that material sets etc. can take into account ...

**Comment by Moult** [comment]
For now as a workaround you may use pattern or enumeration restriction.

**Comment by hesrah** [comment]
Yes, I see. But it's not really a (good) workaround. It's what we have anyway, and it doesn't mean there are necessarily two materials.
Anyway, there is no other option at the moment.

**Comment by aothms** [comment]
Can't two material facets be emulated using two separate specifications with identical applicabilities?

You can also require walls as decompositions of IfcBuildingElementParts, not sure if you're able to express your requirements in that case with a combination of `partOf` and `material`.

I think this use case is a bit on the intersection of data requirement vs design requirement. Next question would be, knowing which material is the outside one. So I think I'm ok with not perfectly supporting this atm, but there's definitely a blind spot still in IDS with layered/constituent materials, their behaviour in terms of existence vs universal qualification (all vs any).

**Comment by hesrah** [comment]
I've thought about that too. But if you say "innermaterial='WOOD' AND outermaterial='CONCRETE'" in two separate specification elements, each material must be wood and concrete at the same time! It must be schizophrenic material. ;-)

Yes, that's the other problem of the use case: You can't really differentiate between inner and outer material. I think, the best way would be an IfcMaterialLayer for the wall. This is a design requirement first, and generates a data requirement second.

I think material requirement is a bit complicated and we need to discuss this in detail for an upcoming IDS release.

**Comment by aothms** [comment]
> I've thought about that too. But if you say "innermaterial='WOOD' AND outermaterial='CONCRETE'" in two separate specification elements, each material must be wood and concrete at the same time! It must be schizophrenic material. ;-)

But wouldn't that be the same with two facets?

@Moult please correct me if I'm wrong, but I thought the behaviour for compound materials is that the requirement passes when **1 or more** of the materials in the compound match the requirement. So two specs or two facets would behave the same? And two separate specs would work in this case?

> I think material requirement is a bit complicated and we need to discuss this in detail for an upcoming IDS release.

Agreed.

**Comment by Moult** [comment]
You are correct. It is an "Any" match. It would be neater to allow multiple facets, of course, and I don't quite understand why we don't do that in IDS v1.

**Comment by aothms** [comment]
I agree, at first sight it diverges a bit from the IFC spec, but because IDS explodes compound materials to top-level members it makes sense indeed to allow multiple facets.

**Comment by hesrah** [comment]
> But wouldn't that be the same with two facets?

I'm still not sure. If this is the same, how can we formulate this use case? How can we rephrase the requirement "innermaterial='WOOD' AND outermaterial='WOOD'" in such a way that you are really sure that there are two materials?
I think you can't with two separate specification but with one specification which have two material facets. (?)

**Comment by hesrah** [comment]
Or is only <material minOccurs="2" ..."> (which is currently not allowed) the way to do it?

**Comment by hesrah** [comment]
> it makes sense indeed to allow multiple mtl facets.

If two separate specification elements and two material facets in one specification is the same, then we don't need both. The use case cannot be covered by either of the two options. Multiple facets therefore make no/little sense, we can believe it by enumerations.
Tell me if I'm wrong.

**Comment by Moult** [comment]
You are wrong in two aspects: enumerations are not equivalent. E.g. requiring material="WOOD|CONCRETE" means that layer1=WOOD and layer2=RABBIT will pass, whereas requiring material="WOOD" in 1 facet and material="CONCRETE" in another facet will fail.

The second aspect is that IDSes are meant to be read by humans, so although multiple facets and multiple specs are logically equivalent, they are not "expressively" equivalent. It would seem weird to repeat the requirement when it would be more expressive to just specify it one spec. But this is purely an opinionated stance.

**Comment by berlotti** [comment]
Correct me if I'm wrong... but I think @hesrah means something else.
When we have 2 'specifications' where one defines a wall with a material requirement, and another one with the same (kind of) wall, but with a different material requirement. That is in fact the same result as one specification with two material requirements. 
Although I don't want to add complexity in the material facet, this is a good point.

**Comment by Moult** [comment]
Yes it is logically equivalent, but "expressively" the grouping feels weird:

 1. All wall types W01 should have both wood and concrete <-- 1 spec, 2 material facets, nice.

Compared to:

 1. All wall types W01 should have wood and concrete <-- 1 spec, 1 facets
 2. All wall types W01 should have concrete <-- 1 spec, 1 facet ... user goes "huh?"

**Comment by hesrah** [comment]
@berlotti: Right.

> we can believe it by enumerations

Agree, I know that an enumeration is not the same as two specification elements (or two material facets in one specifcation). I tried to say we're getting no further than doing the imperfect workaround with an enumeration. None of the variants cover the use case. I don't want to say they are logically equivalent.

**Comment by hesrah** [comment]
@Moult ([last comment](https://github.com/buildingSMART/IDS/issues/92#issuecomment-1260654187)):
I still believe that if "two specs" is the same as "two material facets in one spec" then you have schizophrenic material in both ways. 
So far I have understood that two specifications in IDS are linked in an AND logic.(?)

**Comment by hesrah** [comment]
Maybe I should ask the question differently: How can I count material information?

Obviously I can't do that with multiple specifications.
I believe we should read multiple material facets (if they are allowed) in such a way that we can "count" material information.

Anyway my brain is smoking ...

**Comment by Moult** [comment]
If you know you need 2 materials, wood and concrete, right now you can use two specs: one asking for wood, the other for concrete. It's not foolproof, as it won't protect against a material named wood under the concrete category, and also not protect against having >2 materials. You also cannot specify whether it is an inner layer or outer layer or constituent percentage or profile vs layer vs constituent.

**Comment by hesrah** [comment]
Ok, but then "any" match is not compatible with 

> two specifications in IDS are linked in an AND logic

"any" match is an OR logic?

**Comment by hesrah** [comment]
Ok, I think I understand what you mean.

**Comment by hesrah** [comment]
> 1. All wall types W01 should have wood <-- 1 spec, 1 facets
> 2. 3.All wall types W01 should have concrete <-- 1 spec, 1 facet ... user goes "huh?"

Yes, I don't think any user understands that ...
So it would be nice to have multiple material facets yet.

**Comment by hesrah** [comment]
The more I think about it, I come to the conclusion that we _have to_ reject the limitation on one material facet. We have a restriction that we cannot hold. This is a senseless restriction.

**Comment by Moult** [comment]
I also am in favour of removing the limitation.

**Comment by hesrah** [comment]
If we can't hold the limitation (because of the workaround with two specification elements), the limitation's only job is to generate unreadable IDS files.

**Comment by TLiebich** [comment]
+1

**Comment by berlotti** [comment]
I really like this discussion. Specially the input from @hesrah  about adding two requirements to get the same result of adding multiple matials.
It is clear that we have to deal with this.

However... we said the 1.0 would be based on what we got from the use-cases from the first phase. In those use-cases there is only one material requirement. 

So my suggestion is to put this on the roadmap for 1.1 (or whatever next version) so we have time to collect use-cases as input to model this properly.
It would be great if you can share the documents from practise that require multiple/layered materials in the use-cases folder in this repo.

**Comment by hesrah** [comment]
From a puritanical formalism perspective, this is actually a design fault.

From a softer perspective, we disscused it as a recommendation. We promise not to use the workaround. ;-)
And if you have a more complex material requirement, you cann't express it with two material requirements anyway. Two simple materials say nothing about layer, component or profile set structure.

A future version should have more powerful posibilities to form such more complex requirements.
The current version is a bit modest for material requirements, but we cannot simply change this aspect by adding more material facet in a requirement item. That would require more structural changes.
