### ISSUE TITLE
Data Type or Measure

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#93]
Documentation on https://github.com/buildingSMART/IDS/blob/master/Documentation/property-facet.md uses the term "Data Type", but the schema uses "measure". I think using the same term would be better. Don't have a preference.

**Comment by Moult** [comment]
I used the term data type in the docs to try and cater for more common language that users would understand. "Data type" is a well established concept, whereas the nuance of a "Measure" (measure type?) I guess occurred when originally it was intended for just measures but now it extends to non-measurement types too (IfcLabel, IfcBoolean, etc).

**Comment by CBenghi** [comment]
Agreed to close in call.
