### ISSUE TITLE
Testcase "[PASS] An optional facet always passes regardless of outcome 1 & 2/2"

### ISSUE THREAD

**Issue by hesrah** [buildingSMART/IDS#94]
[[PASS] An optional facet always passes regardless of outcome 1/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-classification.md#pass-an-optional-facet-always-passes-regardless-of-outcome-12)
[[PASS] An optional facet always passes regardless of outcome 2/2](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-classification.md#pass-an-optional-facet-always-passes-regardless-of-outcome-22)

It's a attribute testcase in the classification testcase chapter. -> Move or change.

**Comment by Moult** [comment]
Changed to be classification optionality. Thanks!
