### ISSUE TITLE
QUDT column in units table

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/IDS#95]
Not really an issue but more of a question about the provided table: 
https://github.com/buildingSMART/IDS/blob/master/Documentation/units.md

My assumption is that the value provided in the column name "QUDT" is what should be used in the "measure" attribute of 
"propertyType".

Since there seems to be a 1-1 mapping between IFC type to QUDT in this table, would using the IFC type directly in the IDS not make more sense, or perhaps I am missing something?

**Comment by Moult** [comment]
The IFC type should be used directly in the measure attribute. See test cases: https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md

Maybe the QUDT column can be deleted?

**Comment by rubendel** [comment]
Ok thanks Dion, will use that. Indeed sounds like QUDT column can be deleted, happy to that after perhaps response from @CBenghi who I think created the original table?

**Comment by aothms** [comment]
I think there's value to this column for some people, but it bears no significance to the current version of IDS and there is little reason to maintain it within the IDS project if you ask me. This could be moved to an informative section in the IFC docs.

**Comment by CBenghi** [comment]
A few minutes ago, in the call (currently ongoing) consensus was to remove it, because not immediately useful for the specs.
