### ISSUE TITLE
Entity name in uppercase

### ISSUE THREAD

**Issue by ciroraggio** [buildingSMART/IDS#98]
From the tests and documentation it is understood that entities must be specified in uppercase, but in many tests we find the applicability entities in camel case, while in requirements the entity name is in upper. 
Example: fail-restrictions_an_be_specified_for_the_predefined_type_3_3.ids.
Is this correct? If so, why? What is the difference?

**Comment by Moult** [comment]
No, it's a typo from an earlier version of the test suite, I'll update it.

**Comment by Moult** [comment]
Fixed, commit incoming.
