### ISSUE TITLE
Questions about optionality

### ISSUE THREAD

**Issue by ciroraggio** [buildingSMART/IDS#99]
I have come across this case (fail-a_prohibited_facet_returns_the_opposite_of_a_required_facet) which I do not know whether I have fully understood.

```
     <specification name="A prohibited facet returns the opposite of a required facet" ifcVersion="IFC2X3 IFC4" minOccurs="1 maxOccurs="1"> // required
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IFCWALL</simpleValue>
                    </name>
                </entity>
            </applicability>
            <requirements>
                <classification minOccurs="0" maxOccurs="0" /> // prohibited
            </requirements>
        </specification>
```

Based on your documentation regarding XSD optionality, I understand that this test should fail because the request is to have no classified walls in general, but there are some classified walls in the IFC file. Is this correct?

Another case that is not very clear, is when you have a set of requirements (prohibited and required) for a prohibited specification. In this case, should the requirements be understood in reverse (the prohibited become required and the required become prohibited) or is there another logic to follow?

**Comment by Moult** [comment]
This is due to a bug in the test case generation, commit incoming which now explicitly makes all the entities different classes so there is no ambiguity.
